### ISSUE TITLE
Airbus I could nut run the scraper

### ISSUE THREAD

**Issue by cornel13** [peviitor-ro/validator-ui#100]
ENVIRONMENT:

https://admin.peviitor.ro/account
browser: chrome
STEPS TO REPRODUCE:

Enter url in browser

Try to manually run the scraper Airbus

EXPECTED RESULTS:
The scraper should run without issues

ACTUAL RESULTS:
The scraper does not run and pop an error
Attachments:

**Comment by lalalaurentiu** [comment]
Fixed
