### ISSUE TITLE
A message should appear telling that the email is not valid or does not exist 

### ISSUE THREAD

**Issue by LucianLCI** [peviitor-ro/validator-ui#107]
URL: https://admin.peviitor.ro/login
Browser: Chrome
Device: PC
OS: Windows 10

Steps to reproduce:
1.Open Chrome
2.The user clicks on the search bar the admin URL
3.The user writes the email incomplete
Expected result:
A message should appear telling that the email is not valid or does not exist 
Actual result: An email was sent to an incorrect/bad email address.

**Comment by lalalaurentiu** [comment]
Added...
