### ISSUE TITLE
Modify the link from the Validator page in the ,,Despre'' section to open the Organization page not the peviitorpage.

### ISSUE THREAD

**Issue by LucianLCI** [peviitor-ro/validator-ui#108]
URL:https://admin.peviitor.ro/
Browser: Chrome
Device: PC
OS: Windows 10

Steps to reproduce:
1.Open Chrome
2.Log in Validator
3.After Logging in, in the validator press on the Despre Button
Expected result:
The ,,Ascociatia Oportunitati si Cariere'' main page should appear.
Actual result: A message containing  ,,Ignore'' and peviitor.ro appears.

**Comment by lalalaurentiu** [comment]
Fixed
