### ISSUE TITLE
TC Verification of the search functionality with uppercase letters

### ISSUE THREAD

**Issue by SimonaNemtanu** [peviitor-ro/validator-ui#119]
Description: Validator main page content
Preconditions: Peviitor validator page is opened

**Comment by SimonaNemtanu** [comment]
Step 1:

    Ensure that the search bar is visible.

**Comment by SimonaNemtanu** [comment]
Step 2:

    Enter uppercase letters (e.g., "TEST") into the search bar.

**Comment by SimonaNemtanu** [comment]
Step 3:

Click the search button or press the Enter key.

**Comment by SimonaNemtanu** [comment]
Expected Result: The search results corresponding to the entered uppercase letters appear on the page.

**Comment by Lore78** [comment]
Tested on Chrome [(laptop-Windows 11), (tablet-Android) and (telephone-Android)]
