### ISSUE TITLE
ALSO- different job counts on admin.peviitor.ro and peviitor.ro

### ISSUE THREAD

**Issue by Catalinay** [peviitor-ro/validator-ui#121]
**ENVIRONMENT**:
Production URL: https://admin.peviitor.ro/
Browser: Chrome
Device: PC
OS: Windows 10

**STEPS TO REPRODUCE:**

1. Open URL https://admin.peviitor.ro/ in the browser.
2. Go to "Cont" and run the scraper for the company "also.py".
3. Go to "Companii" and type "also" in the search bar.
4. Click on the "Vizualizeaza joburi" button.
5. Verify the number of jobs displayed
6. Open URL https://peviitor.ro/ in the browser.
7. Search for "also" on the user site.
8. Verify the number of jobs displayed 

**EXPECTED RESULT:**
The number of jobs on https://admin.peviitor.ro/ matches the number of jobs on the official website https://peviitor.ro/. 

**ACTUAL RESULT:**
The number of jobs displayed on [admin.peviitor.ro](https://admin.peviitor.ro/) is **3**.
![image](https://github.com/peviitor-ro/validator-ui/assets/161432647/b0242f14-85ab-4ec7-8b26-e5fe4c0cf62c)
![image](https://github.com/peviitor-ro/validator-ui/assets/161432647/a9ebba6a-1e8b-4e71-8002-c1dea25ebd25)

The number of jobs displayed on the official user site, https://peviitor.ro/ is **5**.
![image](https://github.com/peviitor-ro/validator-ui/assets/161432647/9aec17fb-a913-4c5e-9c71-b5daa1513d6f)

Two additional internship positions are listed on peviitor.ro.
Clicking on "**catre site**" for these two internships returns "**object not found**".
![image](https://github.com/peviitor-ro/validator-ui/assets/161432647/affe31c1-7331-4b14-bd45-f87379384553)

**ADDITIONAL DETAILS:**
There is a discrepancy between the job counts on the admin portal and the user-facing site.
The two additional internship listings appear to be broken links or incorrect entries as they lead to a "**object not found**" error.

**Comment by IurieChi** [comment]
This issue is connected to database synchronization after manual synchronization on the production peviitor.ro are 3 jobs 
<img width="355" alt="Screenshot 2024-07-12 at 12 16 20" src="https://github.com/user-attachments/assets/e8f56c03-b5d3-4734-953e-723f3b472a7c">
<img width="1338" alt="Screenshot 2024-07-12 at 12 18 23" src="https://github.com/user-attachments/assets/83767f17-6565-4081-b43f-2a9958386a40">
