### ISSUE TITLE
The synchronization is not made automatically for many company scraped with JS

### ISSUE THREAD

**Issue by cornel13** [peviitor-ro/validator-ui#124]
ENVIRONMENT:

https://admin.peviitor.ro/account
browser: chrome
STEPS TO REPRODUCE:
For the following company's :Abbvie, Agricover, Airbus, Atlascopco ,Autoliv, Bolt, Borgwarner, Cegeka ,Celestica, Cocacolahbc, Continental, Crowdstrike, Deutschebank, Drmax

The automatically synchronization of the jobs is not working
Enter url in browser

For mentioned company's check if the jobs published on validator match the ones displayed on https://peviitor.ro/

EXPECTED RESULTS:
The jobs published on validator should match the ones displayed on https://peviitor.ro/

ACTUAL RESULTS:
The jobs published on validator does not match with the ones displayed on https://peviitor.ro/ and are many jobs unavailable on the company's site but displayed on https://peviitor.ro/

**Comment by lalalaurentiu** [comment]
you can reproduce it using a video?
