### ISSUE TITLE
Conduent - Different number of jobs from the validator website after rerunning the scraper

### ISSUE THREAD

**Issue by yonutzu** [peviitor-ro/validator-ui#125]
ENVIROMENT: production[
URL: ](https://admin.peviitor.ro/
Browser: Chrome
Device: PC
OS: Windows 11

STEPS TO REPRODUCE:

Open URL in browser
Type "conduent" in the search bar.
Click on "Vizualizeaza joburi" button
Verify the job numbers
Go on "www.peviitor.ro" and running again the scraper.
Verify again the number of jobs.

Expected result:
The number of jobs from the https://admin.peviitor.ro is the same with the number of jobs from the "[www.peviitor.ro](https://peviitor.ro/#/rezultate)"

Actual result:
The number of jobs is different (1 on validator) from the "www.peviitor.ro" (5)

![conduent-validator](https://github.com/user-attachments/assets/f08df573-9992-49bb-a5a7-0e77f4a01012)

![conduent-peviitor](https://github.com/user-attachments/assets/997fa02c-27c1-455a-b9a4-f503e45d3eaf)

**Comment by lalalaurentiu** [comment]
that is input for jobs, this is filter for company
<img width="1440" alt="Screenshot 2024-07-19 at 07 57 14" src="https://github.com/user-attachments/assets/66df34a6-8d5f-4dd3-8339-c58c84360d0f">
