### ISSUE TITLE
Dennemeyer - Different number of jobs from the validator website after rerunning the scraper

### ISSUE THREAD

**Issue by yonutzu** [peviitor-ro/validator-ui#126]
ENVIROMENT: production[
URL: ](https://admin.peviitor.ro/
Browser: Chrome
Device: PC
OS: Windows 11

STEPS TO REPRODUCE:

Open URL in browser
Type "Dennemeyer" in the search bar.
Click on "Vizualizeaza joburi" button
Verify the job numbers
Go on "[www.peviitor.ro](https://peviitor.ro/#/rezultate)" and running again the scraper.
Verify again the number of jobs.

Expected result:
The number of jobs from the https://admin.peviitor.ro is the same with the number of jobs from the "[www.peviitor.ro](https://peviitor.ro/#/rezultate)"

Actual result:
The number of jobs is different (8 on validator) from the "[www.peviitor.ro](https://peviitor.ro/#/rezultate)" (13)

![Dennemeyer-validator](https://github.com/user-attachments/assets/9a316924-2e51-45f3-95f2-0a30d850b438)

![Dennemeyer-peviitor](https://github.com/user-attachments/assets/4b211348-8756-424a-adf4-2bf7647a9c05)

**Comment by lalalaurentiu** [comment]
that is input for jobs, this is filter for company
<img width="1440" alt="Screenshot 2024-07-19 at 07 40 43" src="https://github.com/user-attachments/assets/06ca564a-5d98-4def-a902-8beba13450dc">
