### ISSUE TITLE
TC Verification of the visibility of the sort selection dropdown

### ISSUE THREAD

**Issue by SimonaNemtanu** [peviitor-ro/validator-ui#128]
Description: Validator main page content
Preconditions: Peviitor validator page is opened

**Comment by SimonaNemtanu** [comment]
Step 1:

    Navigate to the Peviitor validator page.

**Comment by SimonaNemtanu** [comment]
Step 2:
   Check if the sort selection dropdown is visible next to the search bar.

**Comment by SimonaNemtanu** [comment]
Expected Result: The sort selection dropdown is visible and easily accessible.

**Comment by Lore78** [comment]
Tested on Chrome [(laptop-Windows 11), (tablet-Android) and (telephone-Android)]
