### ISSUE TITLE
TC Verification of the selection of the "Alphabetic" option

### ISSUE THREAD

**Issue by SimonaNemtanu** [peviitor-ro/validator-ui#129]
Description: Validator main page content
Preconditions: Peviitor validator page is opened

**Comment by SimonaNemtanu** [comment]
Step 1:

    Navigate to the Peviitor validator page.
    Ensure that the sort selection dropdown is visible.

**Comment by SimonaNemtanu** [comment]
Step 2:

    Click on the sort selection dropdown to display the available options.

**Comment by SimonaNemtanu** [comment]
Step 3:

  Select the "Alphabetic" option from the dropdown.

**Comment by SimonaNemtanu** [comment]
Expected Result: The results are sorted alphabetically in ascending order.

**Comment by Lore78** [comment]
Tested on Chrome [(laptop-Windows 11), (tablet-Android) and (telephone-Android)]
