### ISSUE TITLE
Siemenshealthineers - cannot be run the scraper

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#134]
ENVIRONMENT:

https://admin.peviitor.ro/account
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "based_scraper_py"  and make click
Push on "siemenshealthineers.py" and try to run manually this scraper 

EXPECTED RESULTS:
The scraper should run without issues

ACTUAL RESULTS:
The scraper does not run and pop an error
Attachments:

![image](https://github.com/user-attachments/assets/9dc1b743-746b-4774-83f8-83f37e93c8cf)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by Cristian-Emil** [comment]
Tested. Is OK. Work.

![image](https://github.com/user-attachments/assets/f8fa5376-6171-4d40-afae-8925c9e2129b)
