### ISSUE TITLE
Veo - cannot be run the scraper

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#135]
ENVIRONMENT:

https://admin.peviitor.ro/account
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "based_scraper_py" and make click
Push on "veo.py" and try to run manually this scraper

EXPECTED RESULTS:
The scraper should run without issues

ACTUAL RESULTS:
The scraper does not run and pop an error
Attachments:

![image](https://github.com/user-attachments/assets/743dcb5c-b941-447a-b474-342c829f8dbc)

**Comment by lalalaurentiu** [comment]
Fixed.

<img width="1440" alt="Screenshot 2024-07-18 at 17 29 44" src="https://github.com/user-attachments/assets/f25fa3fd-2f34-4407-8b15-75934807cc3d">

**Comment by Cristian-Emil** [comment]
Test done. 
Bug solved.

![image](https://github.com/user-attachments/assets/fd7f721e-3d3d-44b1-8c72-4e214a9fac3d)
