### ISSUE TITLE
TC Validate that the search button in the top menu is visible.

### ISSUE THREAD

**Issue by SimonaNemtanu** [peviitor-ro/validator-ui#138]
Description: Validator main page content
Preconditions: Peviitor validator page is opened

**Comment by SimonaNemtanu** [comment]
Step 1:

    Navigate to the Peviitor validator page.

**Comment by SimonaNemtanu** [comment]
Step 2:

   Ensure that the search button in the top menu is visible.

**Comment by SimonaNemtanu** [comment]
Expected Result: The search button is visible and easily accessible.

**Comment by Lore78** [comment]
Tested on Chrome [(laptop-Windows 11), (tablet-Android) and (telephone-Android)]
