### ISSUE TITLE
The jobs are published as "Nepublicat" in validator after you run the scraper even the jobs are already published

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/validator-ui#141]
URL: https://admin.peviitor.ro/jobs/Mindera
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Observe that there are no published jobs.
3. Open the "https://peviitor.ro".
4. Click on the "Cauta" button
5. Click on the "Companie" button, writhe "Mindera" and seletct it in the search bar.
6. Observe that there are 7 jobs available.

**Mention:** At the beginning I published 7 jobs. After running the scraper, the jobs ( 8 jobs because it was another net job) appeared as unpublished in the validator.
**Mention 2:**: If you are running the scraper when you have 8 jobs and the sraper doesn't have another job to bring, the jobs are remaining as published in validator.

**EXPECTED RESULTS:**
The jobs should appear as public in the validator, even if you run the scraper.

**ACTUAL RESULTS:**
The jobs appear as unpublished in the validator after you run the scraper.

<img width="924" alt="image" src="https://github.com/user-attachments/assets/c5ac2bce-52f6-456b-ba73-153559ceaa80">

<img width="776" alt="image" src="https://github.com/user-attachments/assets/74ea473a-d488-4b5b-a3c0-0b038689775b">

**Comment by lalalaurentiu** [comment]
Fixed
