### ISSUE TITLE
"Qualitest" company- the scraper does not work

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/validator-ui#144]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Click on "Cont"
3. Click on "+" from "based_scraper_py"
4. Click on "qualitest.py" and run the scraper

**EXPECTED RESULTS:**
The scraper should run without issues.

**ACTUAL RESULTS:**
The scraper does not run and pop an error.

<img width="101" alt="image" src="https://github.com/user-attachments/assets/054f2a23-37c2-4194-ae0e-1659b1f2747e">

**Comment by lalalaurentiu** [comment]
Fixed
