### ISSUE TITLE
Job title does not display correctly

### ISSUE THREAD

**Issue by SilviaP27** [peviitor-ro/validator-ui#146]
ENVIROMENT: production
URL: https://admin.peviitor.ro/jobs/Systematic

Browser: Chrome
Device: Asus Intel(R) Pentium(R) 4,00 Go
OS: Windows 10

STEPS TO REPRODUCE:

1.Open "https://admin.peviitor.ro/jobs/Systematic" in the browser.
2.Check "Financial Controller" job title
3.Open https://jobs.systematic.com/job/Bucharest-Financial-Controller/1086649301/
4.Check "Financial Controller" job title

EXPECTED RESULTS:
The job type (hybrid) on both websites are the same.

ACTUAL RESULTS:
The job posted on  Peviitor appears as "On site"  while on the company website it appears as Hybrid 

![image](https://github.com/user-attachments/assets/70ea0f87-c792-42c3-ac86-465ef794e94f)

![image](https://github.com/user-attachments/assets/08cac6f5-2143-4ee4-95ce-a989a1ae1a7c)
@

**Comment by SilviaP27** [comment]
@sebiboga

**Comment by sebiboga** [comment]
@SilviaP27 this is a issue for Validator not for API
Moving this one under the right REPOSITORY

**Comment by lalalaurentiu** [comment]
This is scraper bug, but you can change manually job-type and title , or add the issue to the scraper repository.
