### ISSUE TITLE
The scraper does not load correctly the number of jobs on Sonnentor

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#147]
ENVIRONMENT:

https://admin.peviitor.ro/account
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/jobs/Sonnentor" and click to firs job on "Catre job"
Check number of availabe jobs -"https://www.sonnentor.ro/despre-noi/cariere.html"

EXPECTED RESULTS:
The page shows the same number of jobs as on the validator

ACTUAL RESULTS:
Page from "https://admin.peviitor.ro/jobs/Sonnentor" show one number of jobs , site show different number.
See below both screenshot

Attachments:
Validator:
![image](https://github.com/user-attachments/assets/14a9c1cb-b70a-4556-8a02-ca6355cfed0d)

Site:
![image](https://github.com/user-attachments/assets/5151289b-3e23-4259-a30c-364fc02d40d6)

**Comment by lalalaurentiu** [comment]
Fixed
