### ISSUE TITLE
The scraper does not load correctly the number of jobs on Siemenshealthineers

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#148]
ENVIRONMENT:

https://admin.peviitor.ro/account
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/jobs/Siemenshealthineers" and click to firs job on "Catre job"
Check number of availabe jobs for Romania -"https://jobs.siemens.com/careers?location=Romania&pid=563156120117903&domain=siemens.com&sort_by=relevance&triggerGoButton=true"

EXPECTED RESULTS:
The page shows the same number of jobs as on the validator

ACTUAL RESULTS:
Page from "https://admin.peviitor.ro/jobs/Sonnentor" show one number of jobs , site show different number.
See below both screenshot

Attachments:
Validator:
![image](https://github.com/user-attachments/assets/1ac6a66c-12b8-4d5b-87b8-6dfe1853b116)

Site:
![image](https://github.com/user-attachments/assets/c75b35a3-2808-4a22-bf0f-6c07ea096ed3)

**Comment by lalalaurentiu** [comment]
@Cristian-Emil nu te uiti unde trebuie. Ce-mi arati tu este site-ul  companiei siemens. Scraperul pentru siemenshealthineers isi ia joburi de aici [siemenshealthineers](https://jobs.siemens-healthineers.com/careers?query=Romania&location=Romania&pid=563156116352285&domain=siemens.com&sort_by=relevance&triggerGoButton=true&triggerGoButton=false)
