### ISSUE TITLE
The scraper does not show correct number of jobs for Synevo

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#149]
ENVIRONMENT:

https://admin.peviitor.ro/account
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro" and click to firs job for "Synevo"
Check number of jobs inside the Synevo page  "https://admin.peviitor.ro/jobs/Synevo"

EXPECTED RESULTS:
The page shows the same number of jobs outside and inside the page for Synevo

ACTUAL RESULTS:
Page from "https://admin.peviitor.ro/jobs" show one number of jobs , inside the page "https://admin.peviitor.ro/jobs/Synevo" show different number.
See below both screenshot

Attachments:
Page from Validator for Synevo:
![image](https://github.com/user-attachments/assets/bec9ad6d-3f08-452a-9e4c-5d82e83c654b)

Internal page from Synevo: 
![image](https://github.com/user-attachments/assets/f64a0071-5777-4820-983e-1a09148ba132)

**Comment by lalalaurentiu** [comment]
Fixed
