### ISSUE TITLE
The scraper does not show correct number of jobs for Zentiva

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#151]
ENVIRONMENT:

https://admin.peviitor.ro/account
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to firs job for "Zentiva"
Check number of jobs inside the Zentiva page "https://admin.peviitor.ro/jobs/Zentiva"

EXPECTED RESULTS:
The page shows the same number of jobs outside and inside the page for Zentiva

ACTUAL RESULTS:
Page from "https://admin.peviitor.ro/jobs" show one number of jobs , inside the page "https://admin.peviitor.ro/jobs/Zentiva" show different number.
See below both screenshot

Attachments:
Page from Validator for Zentiva:
![image](https://github.com/user-attachments/assets/035ff0c5-097f-4673-95ca-374a09fa396b)

Internal page from Zentiva:
![image](https://github.com/user-attachments/assets/b23b7caa-7acb-49af-befd-edb37c82ec0d)

**Comment by lalalaurentiu** [comment]
Fixed
