### ISSUE TITLE
The scraper does not show correct number of jobs for Adobe

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#164]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to firs job for "Adobe"
Check number of jobs inside the Adobe page "https://admin.peviitor.ro/jobs/Adobe"

EXPECTED RESULTS:
The page shows the same number of jobs outside and inside the page for Adobe

ACTUAL RESULTS:
Page from "https://admin.peviitor.ro/jobs" show one number of jobs , inside the page "https://admin.peviitor.ro/jobs/Adobe" show different number.
See below both screenshot

Attachments:
Page from Validator for Adobe:
![Captură ecran (67)](https://github.com/user-attachments/assets/4cd26ada-29fc-48a7-91a4-5728db28ff0f)
![Captură ecran (68)](https://github.com/user-attachments/assets/b0063fd1-5dcd-4845-b402-5d88ef6259c1)

**Comment by lalalaurentiu** [comment]
Fixed...
