### ISSUE TITLE
The scraper does not show that the Fullstack Software Development Engineer - Adobe Commerce  job was filled

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#165]
ENVIRONMENT:

https://admin.peviitor.ro/account
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Adobe"
Click on "Fullstack Software Development Engineer - Adobe Commerce" tab on "Catre Job "button"
Check "https://careers.adobe.com/us/en/job/R146686"

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the message "We're sorry… the job you are trying to apply for has been filled."

See below the screenshot

Attachments:
Page from Validator for Adobe:
![Captură ecran (69)](https://github.com/user-attachments/assets/dbf3da24-55fc-45ed-9730-5ff2a5cef983)

**Comment by lalalaurentiu** [comment]
Jobul nu mai este disponibil. Asigură-te ca pornești scraperul înainte de a testa joburile deoarece ele pot fi șterse între timp și scraperele pornesc o dată pe zi.
