### ISSUE TITLE
The scraper does not shot that the job page for Manager MS Payroll Italy has a 404 error

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#179]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "ADP"
Click on "Manager MS Payroll Italy" tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows a 404 error message, followed by "Sorry, we couldn't find the page you requested.
If this is a job link, the position might be closed."
See below the screenshot

Attachment:
Page from Validator for ADP
![Captură ecran (83)](https://github.com/user-attachments/assets/4c2bc7e5-416e-462f-b200-0e0735f49b02)

**Comment by lalalaurentiu** [comment]
Fixed
