### ISSUE TITLE
The scraper does not shot that the job page for Manager Payroll Implementation with French has a 404 error 

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#180]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "ADP"
Click on "Manager Payroll Implementation with French" tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows a 404 error message, followed by "Sorry, we couldn't find the page you requested.
If this is a job link, the position might be closed."
See below the screenshot

Attachment:
Page from Validator for ADP
![Captură ecran (84)](https://github.com/user-attachments/assets/a6ffe295-abc0-4019-9d43-1ba18d1baf7c)

**Comment by lalalaurentiu** [comment]
Jobul nu mai este disponibil
