### ISSUE TITLE
The scraper does not shot that the job page for Marketplace Operations Sr Manager has a 404 error 

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#181]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "ADP"
Click on "Marketplace Operations Sr Manager" tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows a 404 error message, followed by "Sorry, we couldn't find the page you requested.
If this is a job link, the position might be closed."
See below the screenshot

Attachment:
Page from Validator for ADP
![Captură ecran (85)](https://github.com/user-attachments/assets/1d7da701-60de-45e1-b497-51105558389e)

**Comment by lalalaurentiu** [comment]
Jobul nu mai este disponibil
