### ISSUE TITLE
The scraper does not shot that the job page for Payroll Implementation Consultant has a 404 error message

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#182]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "ADP"
Click on "Payroll Implementation Consultant" tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows a 404 error message, followed by "Sorry, we couldn't find the page you requested.
If this is a job link, the position might be closed."
See below the screenshot

Attachment:
Page from Validator for ADP
![Captură ecran (86)](https://github.com/user-attachments/assets/062ac965-d9b1-46f2-8ede-310fe0b1a78f)

**Comment by lalalaurentiu** [comment]
Jobul nu mai este disponibil
