### ISSUE TITLE
The scraper does not shot that the job page for Internal UAT Consultant has a 404 error message

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#184]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "ADP"
Click on "Internal UAT Consultant" tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows a 404 error message, followed by "Sorry, we couldn't find the page you requested.
If this is a job link, the position might be closed." Furthermore, it is a duplicate
See below the screenshot

Attachment:
Page from Validator for ADP
![Captură ecran (91)](https://github.com/user-attachments/assets/1f08bc7b-0d62-4e0d-a8b7-446279b075e3)

**Comment by lalalaurentiu** [comment]
Jobul nu mai este disponibil

**Comment by lalalaurentiu** [comment]
Asta e singurul job care apare cu 404 dar scraperul îl primește de la server. Probabil va dispărea din răspunsul serverului. Nu-l publici
