### ISSUE TITLE
The scraper does not shot that the job page for Payroll Specialist with Italian has a 404 error message

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#187]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "ADP"
Click on "Payroll Specialist with Italian" tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows a 404 error message, followed by "Sorry, we couldn't find the page you requested.
If this is a job link, the position might be closed." Furthermore, it is a duplicate
See below the screenshot

Attachment:
Page from Validator for ADP
![Captură ecran (94)](https://github.com/user-attachments/assets/9ceb3349-10b5-4c3d-b04e-ed7ff2882a31)

**Comment by lalalaurentiu** [comment]
Fixed
