### ISSUE TITLE
The scraper does not show correct number of jobs for ADP

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#188]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to first job for ADP"
Check number of jobs inside the Adobe page "https://admin.peviitor.ro/jobs/ADP"

EXPECTED RESULTS:
The page shows the same number of jobs outside and inside the page for ADP

ACTUAL RESULTS:
Page from "https://admin.peviitor.ro/jobs" show one number of jobs , inside the page "https://admin.peviitor.ro/jobs/ADP" show different number.
See below both screenshot

Attachments:
Page from Validator for ADP
![Captură ecran (95)](https://github.com/user-attachments/assets/2dc88f0a-26fe-47d1-ae2b-7d5fb9ef7240)
![Captură ecran (96)](https://github.com/user-attachments/assets/31fed9b0-b6df-4c84-918a-3f63adec0bdb)

**Comment by lalalaurentiu** [comment]
Fixed
