### ISSUE TITLE
The scraper does not show that the job page for Sales Finance Analyst with French has a 404 error message

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#190]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "ADP"
Click on "Sales Finance Analyst with French" tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows a 404 error message, followed by "Sorry, we couldn't find the page you requested.
If this is a job link, the position might be closed." Furthermore, it is a duplicate
See below the screenshot

Attachment:
![Captură ecran (98)](https://github.com/user-attachments/assets/f24d9f03-2509-41c4-8c13-5b9db2cb4dc1)

**Comment by lalalaurentiu** [comment]
Jobul nu mai este disponibil
