### ISSUE TITLE
The scraper does not show that the job page for Senior Application Security Architect – EMEA – France has a 404 error message

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#191]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "ADP"
Click on "Senior Application Security Architect – EMEA – France" tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows a 404 error message, followed by "Sorry, we couldn't find the page you requested.
If this is a job link, the position might be closed." Furthermore, it is a duplicate
See below the screenshot

Attachment:
From Validator to ADP
![Captură ecran (99)](https://github.com/user-attachments/assets/0f61df85-2128-4e84-850c-d98a1c044bb3)

**Comment by lalalaurentiu** [comment]
Fixed
