### ISSUE TITLE
The scraper does not show that the job page for Software Engineer with French has a 404 error message

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#194]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "ADP"
Click on "Software Engineer with French" tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows a 404 error message, followed by "Sorry, we couldn't find the page you requested.
If this is a job link, the position might be closed." Furthermore, it is a duplicate
See below the screenshot

Attachment:
From Validator to ADP
![Captură ecran (102)](https://github.com/user-attachments/assets/320530e2-c870-4d36-a5c4-06972a94e15c)

**Comment by lalalaurentiu** [comment]
Fixed
