### ISSUE TITLE
The scraper does not show that the job page for Spain Implementation Consultant has a 404 error message

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#195]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "ADP"
Click on "Spain Implementation Consultant" tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows a 404 error message, followed by "Sorry, we couldn't find the page you requested.
If this is a job link, the position might be closed." Furthermore, it is a duplicate
See below the screenshot

Attachment:
From Validator to ADP
![Captură ecran (103)](https://github.com/user-attachments/assets/0782e173-d913-4c5c-92e0-bff796b0f6bf)

**Comment by lalalaurentiu** [comment]
Fixed...
