### ISSUE TITLE
Job don't have location for Romania

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#198]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "SiemensEnergy"
Click on "Development Engineer (f/m/d) HP Blading, Industrial Steam Turbine" tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job - Location Romania

ACTUAL RESULTS:
This job don't have location for Romania.
See below screenshot

![image](https://github.com/user-attachments/assets/8ddd8188-aa98-4a9d-9094-7c3a8f70d2e6)

In file https://admin.peviitor.ro/jobs/Siemensenergy -  job presentation:

![image](https://github.com/user-attachments/assets/6184a5d7-de7e-405c-829e-57fe38b04eb0)

![image](https://github.com/user-attachments/assets/b06b5d1e-c6c7-4764-a812-920fe21b449f)

**Comment by lalalaurentiu** [comment]
Job description indică ca nu este pentru România sau este vag nu-l publici.
