### ISSUE TITLE
Maxcode - Unable to select county name - "Iași"

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/validator-ui#20]
ENVIRONMENT: production
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1 .Open the URL in the browser 
2. Click on the " Levi9 "
3. Open  https://admin.peviitor.ro/jobs/Maxcode
4. Click on the "See Jobs" button.
5. Click on the " To the Job" button.
6. Click on the " Edit" button.
7. Click on the county "Search bar".
8. Type county name " Iași ".

EXPECTED RESULTS:
Under the search bar appears the name of the city and county that was typed.

ACTUAL RESULTS:
Under the search bar appears the name of the city but next to the name of the county appears the message "No county specified".

ATTACHMENTS:

![image](https://github.com/peviitor-ro/validator-ui/assets/71781611/b0237334-da40-4599-8d2f-babd97cca120)

**Comment by lalalaurentiu** [comment]
Fixed
