### ISSUE TITLE
The scraper does not show that Audit Intelligence Data Analyst job was duplicated and posted twice

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#201]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Allianz"
Click on "Audit Intelligence Data Analyst" tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshot

Attachment:
Page from Validator for Allianz
![Captură ecran (108)](https://github.com/user-attachments/assets/bbf2cb3c-2df5-4b8e-b5ff-d412aaedf441)
![Captură ecran (109)](https://github.com/user-attachments/assets/53aa7b93-5453-4348-ad1c-6a37a124f210)
![Captură ecran (110)](https://github.com/user-attachments/assets/5c95f900-75d3-4936-b467-cb5e7a23a14e)

**Comment by lalalaurentiu** [comment]
Joburile sunt disponibile și pe site-ul lor de cariere. Uită-te atent la link ul jobului ca au id uri unice. Nu sunt duplicate.
