### ISSUE TITLE
The scraper does not show that the announcement job for Back-office Junior Customer Service Agent with German was posted 5 times 

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#202]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Allianz"
Click on "Back-office Junior Customer Service Agent with German" tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The pages show the same job announcement at accessing the other 4 tabs
See below the screenshot

Attachment:
Page from Validator for Allianz
![Captură ecran (111)](https://github.com/user-attachments/assets/c8da5acc-4556-48c6-aac6-844b9e4c5cd9)
![Captură ecran (112)](https://github.com/user-attachments/assets/5d998e20-344b-4db3-a9c7-d8aa2b8204f9)
![Captură ecran (113)](https://github.com/user-attachments/assets/7f56b381-e956-4eaf-8b31-48deaebdcc4a)
![Captură ecran (114)](https://github.com/user-attachments/assets/ec8da9b5-a9b3-4610-b2d9-5b11a290b588)
![Captură ecran (115)](https://github.com/user-attachments/assets/94e5d3b4-216e-46dc-9431-000d189dc683)
![Captură ecran (116)](https://github.com/user-attachments/assets/42b578fe-1dc6-42b3-b58b-97f54b23fb13)
![Captură ecran (117)](https://github.com/user-attachments/assets/ddc6dba2-cbd8-4962-82be-7e66bda6246b)

**Comment by lalalaurentiu** [comment]
Jobul nu mai este disponibil, dar din poze par a fi 2 joburi complet diferite. Uită-te atent la link ul jobului ca au id uri unice. Nu sunt duplicate.
