### ISSUE TITLE
The scraper does not show that Controlling Expert job was duplicated and posted twice

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#204]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Allianz"
Click on "Controlling Expert" tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshot

Attachment:
Page from Validator for Allianz
![Captură ecran (120)](https://github.com/user-attachments/assets/717d7e88-9016-4016-aff6-f575d8916234)
![Captură ecran (121)](https://github.com/user-attachments/assets/17eb4c11-b02d-42c7-b3d2-47d1a64ca930)

**Comment by lalalaurentiu** [comment]
În validator apar 3 joburi cu "Controlling Expert" și sunt prezente pe site-ul lor de cariere. Uită-te atent la link ul jobului ca au id uri unice. Nu sunt duplicate.
