### ISSUE TITLE
The scraper does not show that Credit Analyst job was duplicated and posted twice

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#205]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Allianz"
Click on "Controlling Expert" tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshot

Attachment:
Page from Validator for Allianz
![Captură ecran (122)](https://github.com/user-attachments/assets/e8adb4da-d6c6-40aa-aac8-ceffb770b986)
![Captură ecran (123)](https://github.com/user-attachments/assets/cc54f3e3-4825-4f18-a2ca-9492bd1cc192)

**Comment by lalalaurentiu** [comment]
Jobul nu mai este disponibil, dar din poze par a fi 2 joburi complet diferite. Uită-te atent la link ul jobului ca au id uri unice. Nu sunt duplicate.
