### ISSUE TITLE
The scraper does not show that Data Engineer- Process Mining in GCC Bucharest 1 job was duplicated and posted twice

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#206]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Allianz"
Click on "Data Engineer- Process Mining in GCC Bucharest 1" tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshot

Attachment:
Page from Validator for Allianz
![Captură ecran (123)](https://github.com/user-attachments/assets/4f3cc5c2-6823-4c6b-958c-fc51e031185e)
![Captură ecran (124)](https://github.com/user-attachments/assets/796a5076-664f-41d1-a43d-5e2acb2ce3dc)

**Comment by lalalaurentiu** [comment]
Nu ne interesează ce job description au joburile atâta timp cat au id uri unice. Uită-te atent la linkuri și ai să vezi ca sunt joburi complet diferite.
