### ISSUE TITLE
The scraper does not show that Financial Accountant job was duplicated and posted twice

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#207]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Allianz"
Click on "Financial Accountant" tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshot

Attachment:
Page from Validator for Allianz
![Captură ecran (125)](https://github.com/user-attachments/assets/24525271-8b24-4842-af9c-07a83ca1991d)
![Captură ecran (126)](https://github.com/user-attachments/assets/78e473ac-482e-454b-947a-683a66489880)

**Comment by lalalaurentiu** [comment]
În validator apar 3 joburi cu "Financial Accountant" dar toate sunt prezente pe site-ul lor de cariere. Uită-te atent la link ul jobului ca au id uri unice. Nu sunt duplicate.
