### ISSUE TITLE
The scraper does not show that Financial Accountant(Taxation) job was duplicated and posted twice

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#208]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Allianz"
Click on "Financial Accountant(Taxation)" tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshot

Attachment:
Page from Validator for Allianz
![Captură ecran (127)](https://github.com/user-attachments/assets/3d7a3359-83a2-46cb-b184-63667b34123d)
![Captură ecran (128)](https://github.com/user-attachments/assets/8dd3d12f-a237-408e-bfb2-a217fdf92ebd)

**Comment by lalalaurentiu** [comment]
Jobul nu mai este disponibil, dar din poze par a fi 2 joburi complet diferite. Uită-te atent la link ul jobului ca au id uri unice. Nu sunt duplicate.
