### ISSUE TITLE
The scraper does not show that Technical Accountant in GCC Bucharest job was duplicated and posted twice

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#209]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Allianz"
Click on "Technical Accountant in GCC Bucharest" tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshot

Attachment:
Page from Validator for Allianz
![Captură ecran (131)](https://github.com/user-attachments/assets/44ba058b-3196-4c39-8b67-6fc257ffff90)
![Captură ecran (132)](https://github.com/user-attachments/assets/e66d5c85-fc8f-4287-8166-7bdd919beb20)

**Comment by lalalaurentiu** [comment]
În validator apare doar un singur job cu "Technical Accountant in GCC Bucharest" probabil celălalt nu mai există pe site-ul de cariere, dar din poze par a fi 2 joburi complet diferite. Uită-te atent la link ul jobului ca au id uri unice. Nu sunt duplicate.
