### ISSUE TITLE
The scraper does not show that Tactical Purchaser with German job was duplicated and posted twice 

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#210]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Allianz"
Click on "Tactical Purchaser with German" tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshot

Attachment:
Page from Validator for Allianz
![Captură ecran (133)](https://github.com/user-attachments/assets/bd90d0d4-8beb-4e4f-ad2c-23ddb1188d7b)
![Captură ecran (134)](https://github.com/user-attachments/assets/41975d48-27f7-4e0b-9d04-3e9f1cbc153a)

**Comment by lalalaurentiu** [comment]
Joburile sunt prezente și pe site-ul lor de cariere. Uită-te atent la link ul jobului ca au id uri unice. Nu sunt duplicate.
