### ISSUE TITLE
The scraper does not show that Specialist evaluare daune job was duplicated and posted twice

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#212]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Allianz"
Click on "Specialist evaluare daune" tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshot

Attachment:
Page from Validator for Allianz
![Captură ecran (137)](https://github.com/user-attachments/assets/a528614b-4531-4a0a-87cb-c9e872e24e9a)
![Captură ecran (138)](https://github.com/user-attachments/assets/49752888-1d44-4506-b799-06d4bd97bc2a)

**Comment by lalalaurentiu** [comment]
În validator apare doar un singur job cu "Specialist evaluare daune" probabil celălalt nu mai există pe site-ul de cariere, dar din poze par a fi 2 joburi complet diferite. Uită-te atent la link ul jobului ca au id uri unice. Nu sunt duplicate.
