### ISSUE TITLE
The scraper does not show that HR Metrics Quality Expert job was duplicated and posted twice 

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#213]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Allianz"
Click on "HR Metrics Quality Expert" tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshots

Attachment:
Page from Validator for Allianz
![Captură ecran (140)](https://github.com/user-attachments/assets/39e7f7b9-f8f1-4800-87c1-5907fd2ae1b9)
![Captură ecran (141)](https://github.com/user-attachments/assets/abdd0447-5263-43b9-b76c-0850665ff357)

**Comment by lalalaurentiu** [comment]
Joburile sunt prezente și pe site-ul lor de cariere. Uită-te atent la link ul jobului ca au id uri unice. Nu sunt duplicate.
