### ISSUE TITLE
The scraper does not show that Identity & Access Management (IAM) Specialist job was duplicated and posted twice

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#214]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Allianz"
Click on "Identity & Access Management (IAM) Specialist tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshots

Attachment:
Page from Validator for Allianz
![Captură ecran (142)](https://github.com/user-attachments/assets/51ef7669-11c5-4354-b279-903211872dc0)
![Captură ecran (143)](https://github.com/user-attachments/assets/3aabe817-c663-405c-b56a-94846b237f17)
![Captură ecran (144)](https://github.com/user-attachments/assets/3cbfac96-83e1-4188-a99a-cd9018902c5b)

**Comment by lalalaurentiu** [comment]
În validator apare doar un singur job cu "Identity & Access Management (IAM) Specialist" probabil celălalt nu mai există pe site-ul de cariere, dar din poze par a fi 2 joburi complet diferite. Uită-te atent la link ul jobului ca au id uri unice. Nu sunt duplicate.
