### ISSUE TITLE
The scraper does not show that  Incident Manager CTA (Cat Target Architecture) job was duplicated and posted twice

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#215]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Allianz"
Click on "Incident Manager CTA (Cat Target Architecture)"tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshots

Attachment:
Page from Validator for Allianz
![Captură ecran (145)](https://github.com/user-attachments/assets/70a66dd2-f0ec-42ca-b221-abd6ab019652)
![Captură ecran (146)](https://github.com/user-attachments/assets/87f1ed4c-db7e-4b40-be62-7af4b6414f25)

**Comment by lalalaurentiu** [comment]
Jobul nu mai este disponibil, dar din poze par a fi 2 joburi complet diferite. Uită-te atent la link ul jobului ca au id uri unice. Nu sunt duplicate.
