### ISSUE TITLE
The scraper does not show that Information Risk Management Expert (Fit-Gap Analysis) job was duplicated and posted twice

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#216]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Allianz"
Click on " Information Risk Management Expert (Fit-Gap Analysis)"tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshots

Attachment:
Page from Validator for Allianz
![Captură ecran (147)](https://github.com/user-attachments/assets/5cf378d5-ca30-4930-ad96-4bba34e66860)
![Captură ecran (148)](https://github.com/user-attachments/assets/65696fa6-4311-4bfa-8dad-afb5488c600b)

**Comment by lalalaurentiu** [comment]
În validator apare doar un singur job cu "Information Risk Management Expert (Fit-Gap Analysis)" probabil celălalt nu mai există pe site-ul de cariere, dar din poze par a fi 2 joburi complet diferite. Uită-te atent la link ul jobului ca au id uri unice. Nu sunt duplicate.
