### ISSUE TITLE
The scraper does not show that IT Risk Manager IRM job was multiplied and posted three times

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#217]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Allianz"
Click on " IT Risk Manager IRM "tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshots

Attachment:
Page from Validator for Allianz
![Captură ecran (149)](https://github.com/user-attachments/assets/906e66cd-e4c2-4c3b-a342-cd96fcb88f8c)
![Captură ecran (150)](https://github.com/user-attachments/assets/d94f3029-8a01-4e4b-a19c-8509cb220250)
![Captură ecran (151)](https://github.com/user-attachments/assets/376ffb39-3334-4e97-9992-3ced32d1bf1d)

**Comment by lalalaurentiu** [comment]
În validator apar 2 din cele 3 joburi menționate cu "IT Risk Manager IRM" care apar și pe site-ul lor de cariere. Uită-te atent la link ul jobului ca au id uri unice. Nu sunt duplicate.
