### ISSUE TITLE
The scraper does not show that MRC Broker job was multiplied and posted three times 

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#218]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Allianz"
Click on " MRC Broker "tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshots

Attachment:
Page from Validator for Allianz
![Captură ecran (152)](https://github.com/user-attachments/assets/ce2f9048-e424-4373-b866-5f637197c303)
![Captură ecran (153)](https://github.com/user-attachments/assets/bf253976-0c76-4755-bc63-5f6cfb68c0c9)

**Comment by lalalaurentiu** [comment]
În validator apare doar un singur job cu "MRC Broker" probabil celălalt nu mai există pe site-ul de cariere, dar din poze par a fi 2 joburi complet diferite. Uită-te atent la link ul jobului ca au id uri unice. Nu sunt duplicate.
