### ISSUE TITLE
The scraper does not show that Personal Assistant job was duplicated and posted twice

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#219]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Allianz"
Click on "Personal Assistant "tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshots

Attachment:
Page from Validator for Allianz
![Captură ecran (154)](https://github.com/user-attachments/assets/66f04108-7d59-47ad-b7b3-6d9cbd3e428c)
![Captură ecran (155)](https://github.com/user-attachments/assets/7a836bde-8f82-48fd-a69c-c57e5b80181e)

**Comment by lalalaurentiu** [comment]
În validator apar 4 joburi cu "Personal Assistant" dar toate sunt prezente pe site-ul lor de cariere . Uită-te atent la link ul jobului ca au id uri unice. Nu sunt duplicate.
