### ISSUE TITLE
The scraper does not show that Risk& Internal Control Manager job was duplicated and posted twice

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#221]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Allianz"
Click on "Risk&Internal Control Manager "tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshots

Attachment:
Page from Validator for Allianz
![Captură ecran (158)](https://github.com/user-attachments/assets/9ed00eba-3d82-42e3-b910-00fd5d6a2f04)
![Captură ecran (160)](https://github.com/user-attachments/assets/027a88ca-9659-4b0b-8231-c480fa344aac)

**Comment by lalalaurentiu** [comment]
Jobul nu mai este disponibil, dar din poze par a fi 2 joburi complet diferite. Uită-te atent la link ul jobului ca au id uri unice. Nu sunt duplicate.
