### ISSUE TITLE
The scraper is does not synchronize  the job list  (Loreal)

### ISSUE THREAD

**Issue by LucianLCI** [peviitor-ro/validator-ui#226]
https:[//admin.peviitor.ro/]
Browser: Chrome
Device: PC
OS: Windows 10

STEPS TO REPRODUCE:
Enter URL in browser: [//admin.peviitor.ro/]
In go to https://admin.peviitor.ro/jobs/Loreal
Click on synchronize Job List

EXPECTED RESULTS:
The job list should synchronized with the jobs from the Loreal job list

ACTUAL RESULTS:
The job list is not synchronizing and one job is missing (Consultant Vanzari Kiehl's Promenada)

**Comment by lalalaurentiu** [comment]
Fixed..
