### ISSUE TITLE
The scraper does not show that Process Mining Expert job was duplicated and posted twice

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#227]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Allianz"
Click on "Process Mining Expert "tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshots

Attachment:
Page from Validator for Allianz
![Captură ecran (165)](https://github.com/user-attachments/assets/6031cb0e-fb29-454b-a802-d4102875eb80)
![Captură ecran (166)](https://github.com/user-attachments/assets/4b96d35b-1911-4f04-8bd0-238865b542be)

**Comment by lalalaurentiu** [comment]
Nu ne interesează cum își scriu firmele job descrtion atâta timp cat joburile au id uri unice. Asta înseamnă ca sunt 2 joburi complet diferite
