### ISSUE TITLE
"Sterge" button to delete company from validator and all jobs in production 

### ISSUE THREAD

**Issue by IurieChi** [peviitor-ro/validator-ui#228]
ENVIRONMENT: production
URL: https://admin.peviitor.ro/
Browser: Brave
Device: Laptop
OS: Mac OS

DESCRIPTION:

When you click on "Delete", a company needs to delete all jobs from production.  It is necessary to avoid manually job deleting jobs from production.

EXPECTED RESULTS:
When you press the "Sterge" button,  should delete the company from validating and all published jobs from production.

ACTUAL RESULTS:
When you press the "Sterge" button, the company is automatically deleted without deleting all jobs from production.

**Comment by lalalaurentiu** [comment]
Fixed...

**Comment by IurieChi** [comment]
working
