### ISSUE TITLE
The scraper does not show that Financial Accountant with French - Treasury & Bank Accounting job was duplicated and posted twice

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#229]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10Financial Accountant with French - Treasury & Bank Accounting

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Allianz"
Click on " "tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshots

Attachment:
Page from Validator for Allianz
![Captură ecran (167)](https://github.com/user-attachments/assets/fbc47d23-b95d-4ce3-a1bb-affa64bff745)
![Captură ecran (168)](https://github.com/user-attachments/assets/bf8f4f94-568c-4726-88ca-eb2c29d63999)

**Comment by lalalaurentiu** [comment]
În validator apare doar un singur job cu "Financial Accountant with French - Treasury & Bank Accounting" probabil celălalt nu mai există pe site-ul de cariere, dar și poze par a fi 2 joburi complet diferite. Uită-te atent la link ul jobului ca au id uri unice. Nu sunt duplicate.
