### ISSUE TITLE
Autonom - Analist Servicii Client - City and county doesn't match : "Cluj-Napoca, Zalau"

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/validator-ui#23]
ENVIRONMENT: production
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1 .Open the URL in the browser
2. Click on the **" Autonom "**
3. Open  https://admin.peviitor.ro/jobs/Autonom
4. Click on the **" To the Job"** button.
5. Open page https://www.autonom.ro/cariere/job/analist-servicii-client/cluj-napoca
6. See job location .

EXPECTED RESULTS:
Job location, city and county match.

ACTUAL RESULTS:
City and county doesn't match : "Cluj-Napoca, Zalau"

ATTACHMENTS:

![image](https://github.com/peviitor-ro/validator-ui/assets/71781611/0b6d3250-e2ce-42ff-ba70-388ff42ae288)

![image](https://github.com/peviitor-ro/validator-ui/assets/71781611/beae0351-b9ac-492c-81be-5dc4c111bfd2)

**Comment by lalalaurentiu** [comment]
Le poți adăuga manual dacă nu corespund

**Comment by Geo843** [comment]
ok, multam :)
