### ISSUE TITLE
The scraper does not show that Identity and Access Management Expert job was duplicated and posted twice

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#230]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Allianz"
Click on "Identity and Access Management Expert "tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshots

Attachment:
Page from Validator for Allianz
![Captură ecran (169)](https://github.com/user-attachments/assets/f1db7219-b46e-4a96-b2ac-da81b1d32bd8)
![Captură ecran (170)](https://github.com/user-attachments/assets/7544c06e-2b90-40ad-8c42-4fb50daa68dc)

**Comment by lalalaurentiu** [comment]
În validator apare doar un singur job cu "Identity and Access Management Expert" probabil celălalt nu mai există pe site-ul de cariere, dar și poze par a fi 2 joburi complet diferite. Uită-te atent la link ul jobului ca au id uri unice. Nu sunt duplicate.
