### ISSUE TITLE
The scraper does not show that Project Delivery Manager job was duplicated and posted twice

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#231]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Arcadis"
Click on "Project Delivery Manager "tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshots

Attachment:
Page from Validator for Arcadis
![Captură ecran (171)](https://github.com/user-attachments/assets/88ef3ea5-961d-420a-8fd3-500302e72851)
![Captură ecran (172)](https://github.com/user-attachments/assets/fa50b18e-d9e1-4869-8d6e-6cc353f10890)

**Comment by lalalaurentiu** [comment]
În validator apare doar un singur job cu "Project Delivery Manager" probabil celălalt nu mai există pe site-ul de cariere, dar și poze par a fi 2 joburi complet diferite. Uită-te atent la link ul jobului ca au id uri unice. Nu sunt duplicate.
