### ISSUE TITLE
The scraper does not show that the job posted is another one on website compared with on validator

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#232]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Arcadis"
Click on "Quantity Surveyor "tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of another job announcement
See below the screenshots

Attachment:
Page from Validator for Arcadis
![Captură ecran (173)](https://github.com/user-attachments/assets/a83baaf4-94c6-456d-8ad2-2c60aeee35fb)
![Captură ecran (174)](https://github.com/user-attachments/assets/4c505aeb-953e-4de5-8b43-ddcd9e7dff7e)

**Comment by lalalaurentiu** [comment]
Jobul nu mai este disponibil.
