### ISSUE TITLE
The scraper does not show that Roads Design Engineer job was duplicated and posted twice 

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#233]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Arcadis"
Click on "Project Delivery Manager "tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshots

Attachment:
Page from Validator for Arcadis
![Captură ecran (175)](https://github.com/user-attachments/assets/fdac4d4c-ca2a-466c-ab59-437d0c172c70)
![Captură ecran (176)](https://github.com/user-attachments/assets/2a523e53-c533-48e6-847d-85816dc53386)

**Comment by lalalaurentiu** [comment]
În validator apare doar un singur job cu "Project Delivery Manager" probabil celălalt nu mai există pe site-ul de cariere, dar din poze par a fi 2 joburi complet diferite. Uită-te atent la link ul jobului ca au id uri unice. Nu sunt duplicate.
