### ISSUE TITLE
The scraper does not show that on validator page for Arcadis it does not appear the daily graph for number of jobs

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#234]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Arcadis"

EXPECTED RESULTS:
The page shows the daily graph with the evolution of the number of the jobs

ACTUAL RESULTS:
The page shows the phrase "Nu exista date pentru aceasta companie in baza de date"
See below the screenshot

Attachment:
Page from Validator for Arcadis
![Captură ecran (177)](https://github.com/user-attachments/assets/7757cd43-c035-43b9-907e-5fccbaf2d6a3)

**Comment by lalalaurentiu** [comment]
Fixed...
