### ISSUE TITLE
The scraper does not show that Brand Executive job was duplicated and posted twice

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#235]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "BAT"
Click on "Brand Executive" tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshots

Attachment:
Page from Validator for BAT
![Captură ecran (178)](https://github.com/user-attachments/assets/d89c4b4a-cb90-4eea-9f20-2c1ac536cb28)
![Captură ecran (179)](https://github.com/user-attachments/assets/fabde0c2-bb8c-4f33-9af2-4e49da9ccd16)

**Comment by lalalaurentiu** [comment]
Nu sunt duplicate , verifica pe siteul companiei si o sa le gasesti pe ambele. Au si id uri diferite
