### ISSUE TITLE
Scarper WTB don't show correct number of jobs.

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#236]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Walter tosto - Wtb"
Click on "Vizualizeaza joburi (16) " , system load 16 jobs

EXPECTED RESULTS:
The page shows all the jobs available on the page of Walter Tosto WTB.

ACTUAL RESULTS:
Check in Walter Tosta Site - available 17 jobs. 
Last job "RESPONSABIL SSM, SU SI MEDIU - (https://www.wtb.ro/job-responsabil-ssm-su-si-mediu/" is not valid on site peviitor.ro

![image](https://github.com/user-attachments/assets/c295a10c-974d-449d-9a7d-bda0327abf73)

![image](https://github.com/user-attachments/assets/fdd891d2-a197-469e-82ce-105df0af6daf)

**Comment by lalalaurentiu** [comment]
Fixed...
