### ISSUE TITLE
Job from peviitor is not valid on Weatherford site

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#237]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Weatherford"
Check on "Global Senior Sourcing Specialist – HR & Third-Party Workers" and cklick on tab "Catre Job "

EXPECTED RESULTS:
The page shows the full description of this job

ACTUAL RESULTS:
Page from Weatherford site return - "Error: The requested job could not be found."
See below screenshot.

![image](https://github.com/user-attachments/assets/48bde96c-21e7-40b4-9318-5931fb38a67e)

**Comment by lalalaurentiu** [comment]
Fixed...
