### ISSUE TITLE
Scraper for Weatherford is not running

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#238]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and check "Weatherford" and click on "Vizualizare joburi (11)".
On the diagram of scraper show is not running from 31.07.2024
Check and click on button "Cont", click on folder "based_scraper_py"  and load all the scraper. 
Check "weatherford.py" and click on label.

EXPECTED RESULTS:
The page shows scraper is working / load

ACTUAL RESULTS:
After running wetaherford.py return error 
See below screenshot.

Not running from 31.07.2024 according to graph.
![image](https://github.com/user-attachments/assets/9da20862-192c-4bf8-83f1-7ade6b510b48)

Return error when click on scraper "weatherdford.py"
![image](https://github.com/user-attachments/assets/25f999fa-1078-43d7-a1e0-dc80f381c889)

**Comment by lalalaurentiu** [comment]
Fixed...
