### ISSUE TITLE
The scraper does not show that Gestionar depozit BACAU job was duplicated and posted twice

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#239]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Arabesque"
Click on "Gestionar depozit BACAU" tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshots

Attachment:
Page from Validator for Arabesque
![Captură ecran (180)](https://github.com/user-attachments/assets/f4f08a47-baeb-4cc7-9227-fb2de7971b2c)
![Captură ecran (181)](https://github.com/user-attachments/assets/8a392b23-761e-4ae4-849b-7d294c915244)

**Comment by lalalaurentiu** [comment]
Nu sunt duplicate , verifica pe siteul companiei si o sa le gasesti pe ambele. Au si id uri diferite
