### ISSUE TITLE
Autonom -  Consultant Servicii Client - City and County doesn't match- "Satu Mare, Oradea"

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/validator-ui#24]
ENVIRONMENT: production
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1 .Open the URL in the browser
2. Click on the **" Autonom "**
3. Open https://admin.peviitor.ro/jobs/Autonom
4. Click on the " To the Job" button.
5. Open page https://www.autonom.ro/cariere/job/consultant-servicii-client/satumare
6. See job location .

EXPECTED RESULTS:
Job location, city and county match - "Satu Mare, Satu Mare"

ACTUAL RESULTS:
City and County doesn't match- "Satu Mare, Oradea"

ATTACHMENTS:

![image](https://github.com/peviitor-ro/validator-ui/assets/71781611/81f4b606-3538-4170-9ef5-d1f2ae733edc)

![image](https://github.com/peviitor-ro/validator-ui/assets/71781611/c73f9b3f-beca-4276-99f6-7fe77911bd74)

**Comment by lalalaurentiu** [comment]
https://github.com/peviitor-ro/validator-ui/assets/67306273/4a5ade75-f913-4427-8824-108df503f4a9
