### ISSUE TITLE
The scraper does not show that Inginer ofertare instalatii electrice Galati job was duplicated and posted twice

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#240]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Arabesque"
Click on "Inginer ofertare instalatii electrice Galati" tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshots

Attachment:
Page from Validator for Arabesque
![Captură ecran (182)](https://github.com/user-attachments/assets/3bc941b5-3c0c-432b-b075-f9b7b788bbbc)
![Captură ecran (183)](https://github.com/user-attachments/assets/5af68ce5-34f1-4fe2-a476-5e11fef486fd)

**Comment by lalalaurentiu** [comment]
Nu sunt duplicate , verifica pe siteul companiei si o sa le gasesti pe ambele. Au si id uri diferite
