### ISSUE TITLE
The scraper does not show that Inginer Ofertare Instalatii Termice si Sanitare-Bucuresti job was duplicated and posted twice

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#241]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Arabesque"
Click on "Inginer Ofertare Instalatii Termice si Sanitare-Bucurestii" tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshots

Attachment:
Page from Validator for Arabesque
![Captură ecran (184)](https://github.com/user-attachments/assets/13844c1e-dd00-4526-b1f6-702bf0a9a2f2)
![Captură ecran (185)](https://github.com/user-attachments/assets/0070c56f-425a-4489-b255-dc57e259b461)

**Comment by lalalaurentiu** [comment]
That job is no longer available.

![image](https://github.com/user-attachments/assets/dc90ac4d-e1dd-4e38-b135-a287b848294a)
