### ISSUE TITLE
Scraper for Veeam is not running 

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#243]
ENVIRONMENT:
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and check Veeam" and click on "Vizualizare joburi (34)".
On the diagram of scraper show is not running from 02.08.2024
Check and click on button "Cont", click on folder "based_scraper_py" and load all the scraper.
Check "veeam.py" and click on label.

EXPECTED RESULTS:
The page shows scraper is working / load

ACTUAL RESULTS:
After running "veeam.py" return error
See below screenshot.

Not running from 02.08.2024 according to graph.
![image](https://github.com/user-attachments/assets/ba70074a-6ffd-47fe-82c5-ba752a24cf82)

Return error when click on scraper "veeam.py"
![image](https://github.com/user-attachments/assets/09594fc1-b747-4535-9da2-8e61901c2264)

**Comment by lalalaurentiu** [comment]
Fixed...
