### ISSUE TITLE
The scraper does not show that Brand Specialist/Account Manager Spanish job was duplicated and posted three times

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#246]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Amazon"
Click on "ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Arabesque"
Click on "Brand Specialist/Account Manager Spanish" tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshots

Attachment:
Page from Validator for Amazon
![Captură ecran (188)](https://github.com/user-attachments/assets/76c5517f-d02f-4123-9076-656916030c4e)
![Captură ecran (189)](https://github.com/user-attachments/assets/7b113a53-b66e-444f-b5c3-f55f50e08fc3)
![Captură ecran (190)](https://github.com/user-attachments/assets/c62bfe90-344b-4bbc-a75d-8330c473f879)

**Comment by lalalaurentiu** [comment]
Nu sunt duplicate , verifica pe siteul companiei si o sa le gasesti pe toate 3. Au si id uri diferite
