### ISSUE TITLE
The scraper does not show that System Development Engineer job was duplicated and posted twice

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#249]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Amazon"
Click on "ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Arabesque"
Click on "System Development Engineer" job tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshots

Attachment:
Page from Validator for Amazon
![Captură ecran (195)](https://github.com/user-attachments/assets/d93f1943-3d81-46ce-ad02-89c1f78cb280)
![Captură ecran (196)](https://github.com/user-attachments/assets/46383266-be52-43a8-9077-727ff2a96773)

**Comment by lalalaurentiu** [comment]
Nu sunt duplicate , verifica pe siteul companiei si o sa le gasesti pe ambele. Au si id uri diferite
