### ISSUE TITLE
Autonom -Junior Departament Sustenabilitate - Message" Oooops!  The job is no longer available"

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/validator-ui#25]
ENVIRONMENT: production
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1 .Open the URL in the browser
2. Click on the **" Autonom "**
3. Open https://admin.peviitor.ro/jobs/Autonom
4. Click on the " To the Job" button.
5. Open page https://www.autonom.ro/cariere/job/junior-departament-sustenabilitate/bucuresti
6. See job details.

EXPECTED RESULTS:
The job details appears on the page.

ACTUAL RESULTS:
Message **" Oooops!  The job is no longer available"**

ATTACHMENTS:

![image](https://github.com/peviitor-ro/validator-ui/assets/71781611/3bd55398-2eae-4641-b29f-5e343b916afa)

![image](https://github.com/peviitor-ro/validator-ui/assets/71781611/05b83bf7-3bd4-45b4-b000-125852d8639a)

**Comment by lalalaurentiu** [comment]
Ai rulat Scraperul înainte de al testa?

**Comment by Geo843** [comment]
da, l-am rulat.

**Comment by lalalaurentiu** [comment]
postul nu mai este disponibil nici in validator
