### ISSUE TITLE
The scraper does not show that Software Development Engineer, Software Development Engineer- Content Creation job was duplicated and posted twice

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#250]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Amazon"
Click on "ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Arabesque"
Click on "Software Development Engineer, Software Development Engineer- Content Creation" job tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshots

Attachment:
Page from Validator for Amazon
![Captură ecran (197)](https://github.com/user-attachments/assets/79ed0c5b-9b46-44af-9eea-402b55180ecb)
![Captură ecran (198)](https://github.com/user-attachments/assets/6d44bf78-36a4-4bef-9871-6a8590bf54ae)

**Comment by lalalaurentiu** [comment]
Nu sunt duplicate , verifica pe siteul companiei si o sa le gasesti pe ambele. Au si id uri diferite
