### ISSUE TITLE
The scraper does not show that the Software Development Engineer, Ring AI job was posted four times 

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#251]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Amazon"
Click on "ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Amazon"
Click on "Software Development Engineer, Ring AI" job tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshots

Attachment:
Page from Validator for Amazon
![Captură ecran (199)](https://github.com/user-attachments/assets/264d1dad-7bea-4f6d-b128-e35977307c0d)
![Captură ecran (200)](https://github.com/user-attachments/assets/7b9c9493-3cf5-42db-b78d-6f81b6454ded)
![Captură ecran (201)](https://github.com/user-attachments/assets/00eff3fd-f169-4108-8f78-51511939383d)
![Captură ecran (202)](https://github.com/user-attachments/assets/bca3bda5-f926-475e-9de3-b823397ae893)

**Comment by lalalaurentiu** [comment]
Nu sunt duplicate , verifica pe siteul companiei si o sa le gasesti pe toate 4. Au si id uri diferite
