### ISSUE TITLE
The scraper does not show that the Quality Assurance Engineer, Amazon Games job was posted four times

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#252]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Amazon"
Click on "ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Amazon"
Click on "Quality Assurance Engineer, Amazon Games" job tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshots

Attachment:
Page from Validator for Amazon
![Captură ecran (203)](https://github.com/user-attachments/assets/8faf51c3-b91b-4d52-9142-ad77a8d72e6e)
![Captură ecran (205)](https://github.com/user-attachments/assets/29a463da-d090-4759-8817-b00b3b7d34cb)

**Comment by lalalaurentiu** [comment]
![Screenshot 2024-08-26 at 22 04 09 (2)](https://github.com/user-attachments/assets/30332cbc-40cf-41a3-9fa4-40d851ee21b2)
Nu sunt duplicate , verifica pe siteul companiei si o sa le gasesti pe ambele. Au si id uri diferite
