### ISSUE TITLE
The scraper does not show that the Accounts Payable Analyst job was posted twice

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#253]
ENVIRONMENT:
https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Goodyear"
Click on "Accounts Payable Analyst" job tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshots

Attachment:
Page from Validator for Goodyear
![Captură ecran (206)](https://github.com/user-attachments/assets/c2591faa-6450-4cb2-9ffa-3b8db4406445)
![Captură ecran (207)](https://github.com/user-attachments/assets/2e01c540-f856-4544-9c7f-5862a1f69158)

**Comment by lalalaurentiu** [comment]
Nu sunt duplicate , verifica pe siteul companiei si o sa le gasesti pe ambele. Au si id uri diferite
