### ISSUE TITLE
The scraper does not show that the Senior Project Management Specialist job was posted twice 

### ISSUE THREAD

**Issue by TudorNanuTMTA11** [peviitor-ro/validator-ui#254]
ENVIRONMENT:
https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter url in browser
In go to "https://admin.peviitor.ro/" and click to jobs for "Goodyear"
Click on Senior Project Management Specialist" job tab on "Catre Job "option

EXPECTED RESULTS:
The page shows the full description of the job

ACTUAL RESULTS:
The page shows the same full description of the previous job announcement
See below the screenshots

Attachment:
Page from Validator for Goodyear
![Captură ecran (210)](https://github.com/user-attachments/assets/26fbb425-dabb-4a5e-8dfc-39eefeaf6cdb)
![Captură ecran (211)](https://github.com/user-attachments/assets/9c6d6a8f-8f9a-4fbd-8056-8baab23939df)

**Comment by lalalaurentiu** [comment]
Daca intri pe siteul lor de cariere o sa le gasesti pe ambele.
![Screenshot 2024-08-26 at 21 53 27 (2)](https://github.com/user-attachments/assets/0f839050-4dbf-40b4-9484-351d721f11c6)
Daca te uiti pe fiecare job o sa vezi ca au doua id-uri complet diferite
![Screenshot 2024-08-26 at 21 55 49 (2)](https://github.com/user-attachments/assets/68223c1c-02b9-44ae-a3fb-808eb2b4ce04)
![Screenshot 2024-08-26 at 21 55 56 (2)](https://github.com/user-attachments/assets/f03b0e90-4672-4f4e-b997-5b8973ab9fe4)
Nu sunt duplicate
