### ISSUE TITLE
The ING logo is not visible and neither the job description and the city

### ISSUE THREAD

**Issue by OanaRomina** [peviitor-ro/validator-ui#255]
URL: https://peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
-Open the URL in the browser
-Click on the "Cauta" button
-Click on the "Companii" button, write "ING" and select it in the search bar. 
-Observe that the logo doesn't appear .

EXPECTED RESULTS:
- The Logo must appear, the description and the city where is employed .

ACTUAL RESULTS:
-Nothing is displayed, no description and doesn't appear the city where is employed

![image](https://github.com/user-attachments/assets/43cff82f-2d55-4e95-bb24-0f23adbed98a)

**Comment by lalalaurentiu** [comment]
Fixed...
