### ISSUE TITLE
On the URL - "https://admin.peviitor.ro/" - no logo is valid.

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#256]
ENVIRONMENT:
URL: https://peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
- Enter URL "https://admin.peviitor.ro/" in to the browser
- Press ENTER
- Select on the drop-box "Alfabetic (Desc.)" and validate
- Check the logo and description for all company

EXPECTED RESULTS:
On all the company box must to appear pictures/logo, description, number of jobs.

ACTUAL RESULTS:
No pitures / logo is present. See below screenshot

![image](https://github.com/user-attachments/assets/320b2c4a-9d73-49e8-8866-9e08bdb09bcb)

**Comment by lalalaurentiu** [comment]
Fixed...
