### ISSUE TITLE
Scraper for Zentiva is not running

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#257]
ENVIRONMENT:
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter URL "https://admin.peviitor.ro/" in to the browser
Press ENTER
Select on the top bar "CONT" and click
Check and click on folder "based_scraper_py" and load all the scraper.
Check "zentiva.py" and click on label.

EXPECTED RESULTS:
The page shows scraper is working / load, received confirmation of running 

ACTUAL RESULTS:
After running scraper "zentiva.py" this return error
See below screenshot.

![image](https://github.com/user-attachments/assets/c2b502d9-9946-40cc-a8db-942fe9855427)

**Comment by lalalaurentiu** [comment]
Fixed...
