### ISSUE TITLE
Scraper for Vodafone is not running and page show wrong number of jobs

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#258]
ENVIRONMENT:
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter URL "https://admin.peviitor.ro/" in to the browser
Press ENTER
Select on the top bar "CONT" and click
Check and click on folder "based_scraper_py" and load all the scraper.
Check "vodafone.py" and click on label.

Return to " https://admin.peviitor.ro/"
Select "Vodafone" box and clcik on "Vizualizeaza joburi (130)"
Open page for "Vodafone" and check on chart for jobs. 

EXPECTED RESULTS:
The page shows scraper is working / load, received confirmation of running
Chart show 130 jobs.

ACTUAL RESULTS:
After running scraper "vodafone.py" this return error
See below screenshot.
![image](https://github.com/user-attachments/assets/12043c21-27b9-41bc-af84-aac9b7ee0f10)

"vodafone.py" not running from 14.08.2024 according to chart.
![image](https://github.com/user-attachments/assets/ebee21f7-0ba2-4465-806d-885cb84b792d)

**Comment by lalalaurentiu** [comment]
Fixed....
