### ISSUE TITLE
Auchan -Casier - Message -  404/ NOT FOUND

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/validator-ui#26]
ENVIRONMENT: production
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1 .Open the URL in the browser
2. Click on the " Auchan".
3. Open https://admin.peviitor.ro/jobs/Auchan
4. Click on the " To the Job" button.
5. Open page https://cariere.auchan.ro/auchan/jobs/job-casier/282435
6. See job description.

EXPECTED RESULTS:
Job description are opened.

ACTUAL RESULTS:
Message -  404/ NOT FOUND

ATTACHMENTS:

![image](https://github.com/peviitor-ro/validator-ui/assets/71781611/27952b10-8ac0-46c6-8570-36572a253d34)

![image](https://github.com/peviitor-ro/validator-ui/assets/71781611/69bd500b-6b85-4700-999d-ef55ff892537)

**Comment by lalalaurentiu** [comment]
Postul nu mai este disponibil nici in validator
