### ISSUE TITLE
8X8 - The scraper doesn't return data for company's website (Message: Page not found)

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/validator-ui#27]
ENVIRONMENT: Production
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1 .Open the URL in the browser
2. Check the "8X8" scraper
3. Click on the text box: "Vizualizeaza Website"
4. Open the company website's

EXPECTED RESULTS:
The company website's can opened

ACTUAL RESULTS:
The scraper doesn't return data for "8X8" website  (message is: "Page not found")
The company's website page is active and displayed the  jobs for Romania 

![image](https://github.com/peviitor-ro/validator-ui/assets/127322865/43c24a4e-624a-4927-b76e-aca8e0ff8ac3)
![image](https://github.com/peviitor-ro/validator-ui/assets/127322865/cbaed45a-1a6b-4a8f-9082-798468516e83)

![image](https://github.com/peviitor-ro/validator-ui/assets/127322865/7f3a7522-97d5-419c-8575-ebd66b5f54c0)

**Comment by lalalaurentiu** [comment]
Fixed
