### ISSUE TITLE
Medison - Message  "404 -Page not found"

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/validator-ui#28]
ENVIRONMENT: production
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1 .Open the URL in the browser
2. Click on the " Medison 
3. Open https://admin.peviitor.ro/jobs/www.medisonpharma.com/careers/co/romania/8E.348-3D.200/erp-financial-team-lead/all
4. Click on the " To the Job" button.
5. Open page https://admin.peviitor.ro/jobs/www.medisonpharma.com/careers/co/romania/8E.348-3D.200/erp-financial-team-lead/all
6. See job description.

EXPECTED RESULTS:
Job description is opened.

ACTUAL RESULTS:
Message  "404 -Page not found"

ATTACHMENTS:

![image](https://github.com/peviitor-ro/validator-ui/assets/71781611/6e09bb66-cf91-4cca-9128-306f3d7072f5)

![image](https://github.com/peviitor-ro/validator-ui/assets/71781611/2c376fde-b0fa-4209-a804-57e9a5dc541b)

**Comment by lalalaurentiu** [comment]
Acest post nu mai e disponibil.
