### ISSUE TITLE
Verification of the search bar functionality with special characters ,, ###$$%%(( "

### ISSUE THREAD

**Issue by LucianLCI** [peviitor-ro/validator-ui#282]
ENVIRONMENT:
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: PC
OS: Windows 10

STEPS TO REPRODUCE:
Enter URL "https://admin.peviitor.ro/" in to the browser
Press ENTER Main page opens
Type in the search bar special characters like ,, ###$$%%*(*( " 
Expected result: No companies should appear 
Actual result: All the companies appear

Type again in the search bar special character like " !$%%%%%% "
Expected result: No companies appear

![buh](https://github.com/user-attachments/assets/0469c1f1-d029-4481-be00-2970b44d04be)

![bug 1](https://github.com/user-attachments/assets/b1bd2c3c-d25e-45cc-a736-f379c270eacb)

**Comment by lalalaurentiu** [comment]
Fixed..
