### ISSUE TITLE
Verification of the search bar functionality with special characters  ,, &&&&&&&&& "

### ISSUE THREAD

**Issue by LucianLCI** [peviitor-ro/validator-ui#283]
ENVIRONMENT:
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: PC
OS: Windows 10

STEPS TO REPRODUCE:
Enter URL "https://admin.peviitor.ro/" in to the browser
Press ENTER Main page opens
Type in the search bar special characters like ,, &&&&&&&&& "
Expected result: No companies should appear
Actual result: All the companies appear

![bag 2](https://github.com/user-attachments/assets/dd99128e-623c-46a1-86e5-44b25c9e7013)

**Comment by lalalaurentiu** [comment]
Fixed..
