### ISSUE TITLE
Job "FIELD OPERATOR CH II" not exist on Weatherford job page.

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#287]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter URL in browser
Go to "https://admin.peviitor.ro/" and check "Weatherford" 
Scrolldown until found job "FIELD OPERATOR CH II"
Click on job "FIELD OPERATOR CH II"
Click on "Catre Job"

EXPECTED RESULTS:
The page show valid job on site .

ACTUAL RESULTS:
After click on "Catre Job" page show invalid page / job.

See below screenshot.
![image](https://github.com/user-attachments/assets/3905cf67-bb60-4cb4-9597-2237b2802fa3)

**Comment by lalalaurentiu** [comment]
Fixed
