### ISSUE TITLE
Dropdown menu for "Tipul jobului" section 

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/validator-ui#32]
ENVIRONMENT: production
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: PC
OS: Linux

**STEPS TO REPRODUCE:**

1 .Open the URL in the browser and connect to user.
2. On the page "Companii" type in the searching bar the company you wish to review, for example CBS and enter
3. Click the button "Viuzualizeaza joburi"
4. After you have the jobs displayed, go to one of the jobs and click the button "Editati"
5. See the option "tipul jobului" and verify if there is any drop down which has the options : remote/on-site/hybrid which you could select one of it

**EXPECTED RESULTS:**
At the option "Tipul jobului" from "Editati" section, there is a dropdown menu which has 3 options : remote/hybrid/on-site

**ACTUAL RESULTS:**
At the option "Tipul jobului" there is no dropdown menu, but a text field where you can type from the keyboar the job type.
![tipul_jobului](https://github.com/peviitor-ro/validator-ui/assets/129604131/70bc7607-8379-4a06-b6d8-f0a0dd01d087)

**Comment by lalalaurentiu** [comment]
Added in pull request #58
