### ISSUE TITLE
Allianz Tiriac - 404 error when "Vizualizeaza website" button is used. 

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/validator-ui#33]
ENVIRONMENT: production
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: PC
OS: Windows 10

**STEPS TO REPRODUCE:**

1 .Open the URL in the browser and connect to user.
2. On the page "Companii" type in the searching bar - Allianz-Tiriac and enter
3. In the box of Allianz-Tiriac company click on the button "Vizualizeaza website"

**EXPECTED RESULTS:**
We are redirected on the website of the company.

**ACTUAL RESULTS:**
We are redirected on a 404 page with the title " Ne pare rau, insa aceasta pagina nu este disponibila".

<img width="1246" alt="alliantz tiriac" src="https://github.com/peviitor-ro/validator-ui/assets/129604131/ea492938-4d8a-4a73-a723-eee49c5e42c9">

**Comment by lalalaurentiu** [comment]
Fixed...

**Comment by DeedeeDL** [comment]
retested..PASS..well done !
