### ISSUE TITLE
Hivemq - Message" The job you are looking for is no longer open "

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/validator-ui#34]
ENVIRONMENT: production
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1 .Open the URL in the browser
2. Click on the "Hivemq  "
3. Open  https://admin.peviitor.ro/jobs/Hivemq
4. Click on the "See Jobs" button.

EXPECTED RESULTS:
 The company's page is opened and the job details are there

ACTUAL RESULTS:
Message" The job you are looking for is no longer open "

ATTACHMENTS:

![image](https://github.com/peviitor-ro/validator-ui/assets/71781611/1b99a303-d132-45b9-bbdd-16688adc151d)

![image](https://github.com/peviitor-ro/validator-ui/assets/71781611/e655c03d-5ead-430f-bf89-b004803c2078)

**Comment by lalalaurentiu** [comment]
acest issues nu este pentru validator. Te rog sa-l transferi in repozitoriul din care face parte scraperul.

**Comment by lalalaurentiu** [comment]
all 3 positions work
