### ISSUE TITLE
Microchip  -  Message" The page you are looking for doesn't exist"

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/validator-ui#35]
ENVIRONMENT: production
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1 .Open the URL in the browser
2. Click on the "Microchip  "
3. Open https://wd5.myworkdaysite.com/en-US/recruiting/microchiphr/External/job/Romania---Bucharest/NCG-Software-Applications-Engineer_R4138-23-1
4. Click on the "See Jobs" button.

EXPECTED RESULTS:
The company's page is opened and the job details are there

ACTUAL RESULTS:
Message" The page you are looking for doesn't exist"

ATTACHMENTS:

![image](https://github.com/peviitor-ro/validator-ui/assets/71781611/08b40210-02ef-4515-8f41-fc06019bcfae)

![image](https://github.com/peviitor-ro/validator-ui/assets/71781611/182f6126-e259-4721-bfe2-798598acacad)

**Comment by lalalaurentiu** [comment]
Acest issues nu este pentru validator. Te rog sa-l transferi in repozitoriul din care face parte scraperul.

**Comment by lalalaurentiu** [comment]
That job is no longer available
