### ISSUE TITLE
Secondtex  -Text error "Dorolt" instead of " Dorolț"

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/validator-ui#37]
ENVIRONMENT: production
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1 .Open the URL in the browser
2. Click on the " Secondtex "
3. Open https://admin.peviitor.ro/jobs/Secondtex
4. Click on the "See Jobs" button.

EXPECTED RESULTS:
The company's job location is the same us website company.

ACTUAL RESULTS:
Text error "Dorolt" instead of " Dorolț"

ATTACHMENTS:

![image](https://github.com/peviitor-ro/validator-ui/assets/71781611/e3927355-dcca-47bd-94b1-878b2ea45865)

![image](https://github.com/peviitor-ro/validator-ui/assets/71781611/fed9a724-fb59-4213-9acd-be673bd3cb84)

**Comment by lalalaurentiu** [comment]
Validatorul nu suporta diacritice.
