### ISSUE TITLE
Nefab - Text error "Timisoara/ Timis" instead of " Timișoara / Timiș"

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/validator-ui#38]
ENVIRONMENT: production
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1 .Open the URL in the browser
2. Click on the " Nefab "
3. Open  https://admin.peviitor.ro/jobs/Nefab
4. Click on the "See Jobs" button.

EXPECTED RESULTS:
The company's job location is the same us website company.

ACTUAL RESULTS:
 Text error "Timisoara/ Timis" instead of " Timișoara / Timiș"

ATTACHMENTS:

![image](https://github.com/peviitor-ro/validator-ui/assets/71781611/9ce79fc9-f303-40d0-956c-b8c8f757e8a7)

![image](https://github.com/peviitor-ro/validator-ui/assets/71781611/a20ea70a-e16f-4765-9672-7dd6083341d9)

**Comment by lalalaurentiu** [comment]
Valicatorul nu suporta diacritice
