### ISSUE TITLE
Nefab - Error with the button "Vizualizeaza website"

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/validator-ui#39]
ENVIRONMENT: Production
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1 .Open the URL in the browser
2. Check the "Nefab" scraper
3. Click on the text box: "Vizualizeaza Website"
4. Open the company website's

EXPECTED RESULTS:
The company website's is opened

ACTUAL RESULTS:
We are not redirected on the website of the company, we are redirected to the page https://admin.peviitor.ro/ , where you  can see all the company's name.

ATTACHMENTS:

![image](https://github.com/peviitor-ro/validator-ui/assets/71781611/2b76081b-2491-4734-b1bc-fa6c5bdf0216)

![image](https://github.com/peviitor-ro/validator-ui/assets/71781611/fbb944ef-48f3-4270-b92e-41d34c1fc8ec)

**Comment by lalalaurentiu** [comment]
Fixed
