### ISSUE TITLE
"Leohr" company- the scraper does not work

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/validator-ui#396]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Search for company "Leohr"
3. Click on "Vizualizeaza joburi"

**EXPECTED RESULTS:**
The scraper should run without issues.

**ACTUAL RESULTS:**
The scraper is no longer working properly.

![image](https://github.com/user-attachments/assets/2e7ae610-f614-476f-acd3-9702737b5783)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by Florin201092** [comment]
fixed
