### ISSUE TITLE
"Munch" company- the scraper does not work

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/validator-ui#404]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Search for company "Munch"
3. Click on "Vizualizeaza joburi"

**EXPECTED RESULTS:**
The scraper should run without issues.

**ACTUAL RESULTS:**
The scraper is no longer working properly.

![image](https://github.com/user-attachments/assets/14e1d8a5-41ac-46ee-8cc3-e422e30eb709)

**Comment by lalalaurentiu** [comment]
Fixed
