### ISSUE TITLE
"Napa" company- the scraper does not work

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/validator-ui#405]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Search for company "Napa"
3. Click on "Vizualizeaza joburi"

**EXPECTED RESULTS:**
The scraper should run without issues.

**ACTUAL RESULTS:**
The scraper is no longer working properly.

![image](https://github.com/user-attachments/assets/0056852a-8f01-4c4a-8d1e-72848c20a306)

**Comment by lalalaurentiu** [comment]
Fixat
