### ISSUE TITLE
"Neovision" company- the scraper does not work

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/validator-ui#406]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Search for company "Neovision"
3. Click on "Vizualizeaza joburi"

**EXPECTED RESULTS:**
The scraper should run without issues.

**ACTUAL RESULTS:**
The scraper is no longer working since August 21.

![image](https://github.com/user-attachments/assets/6412087b-f175-43fb-ae25-b2f0a903093c)

**Comment by lalalaurentiu** [comment]
Nu știu al cui e dar e fixat.

**Comment by Florin201092** [comment]
Fixed!
