### ISSUE TITLE
Eduboom- les jobbs on validator than on its company website 

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/validator-ui#41]
ENVIRONMENT: production
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: PC
OS: Linux

**STEPS TO REPRODUCE:**

1 .Open the URL in the browser and login
2. Search for Eduboom company 
3. Click on the button "Vizualizeaza joburi"
4. Verify if the jobs number of Eduboom on admin.peviitor.ro corresponds with the number of jobs from the website company.

**EXPECTED RESULTS:**
The numbers of jobs are the same on both websites.

**ACTUAL RESULTS:**
On Eduboom from admin.peviitor.ro are less jobs (1) than the Eduboom website (2)

![Eduboom1](https://github.com/peviitor-ro/validator-ui/assets/129604131/92b1d49b-893c-420b-9789-f89815c2c4ee)
![eduboom2](https://github.com/peviitor-ro/validator-ui/assets/129604131/c32e5f30-dc71-4760-8ad9-b3ea58e6dbfe)

**Comment by lalalaurentiu** [comment]
acest issues nu este pentru validator. Te rog sa-l transferi in repozitoriul din care face parte scraperul.

**Comment by lalalaurentiu** [comment]
Fixed
![Screenshot 2024-07-29 at 10 26 54 (2)](https://github.com/user-attachments/assets/a4ab21d6-3a3e-40bf-a750-61a38f6c7fd5)
