### ISSUE TITLE
 Cartofisserie - The scraper doesn't return all data. Error working

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/validator-ui#42]
ENVIRONMENT: Production
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1 .Open the URL in the browser
2. Run scraper for "Cartofisserie" Company 
3. Check the data returned by the scraper
4. Check activ jobs 

EXPECTED RESULTS:
The scraper returns all data and it shows the number of valid jobs in the last day

ACTUAL RESULTS:
The scraper doesn't return all data
The active jobs of company aren't returned by the scraper on the https://peviitor.ro/#/rezultate

![image](https://github.com/peviitor-ro/validator-ui/assets/127322865/2ac0b1c8-e244-472c-b65e-fa8124dba419)
![image](https://github.com/peviitor-ro/validator-ui/assets/127322865/0d485431-0ee8-40f8-8e49-07b47e80d2d6)
![image](https://github.com/peviitor-ro/validator-ui/assets/127322865/634fd047-2c4e-4abf-b50f-212e7bca9657)

**Comment by lalalaurentiu** [comment]
Fixed
