### ISSUE TITLE
"Sievo" company- the scraper does not work

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/validator-ui#439]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Search for company "Sievo"
3. Click on "Vizualizeaza joburi"

**EXPECTED RESULTS:**
The scraper should run without issues.

**ACTUAL RESULTS:**
The scraper is no longer working since August 21.

![image](https://github.com/user-attachments/assets/761c6a7f-1cc4-4afc-8d82-8d86ebbaa355)

**Comment by lalalaurentiu** [comment]
Nu știu al cui e dar văd ca e fixat.

**Comment by Florin201092** [comment]
Fixed.
