### ISSUE TITLE
County-Level Selection for Job Listings

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/validator-ui#44]
Introduce a dedicated filter to allow **testers** to add an option that encompass an entire county area. This enhancement will streamline the search process for positions that are not confined to a single city or town within a county as some job listings are advertised for an entire county.

<img width="938" alt="Screenshot 2024-05-14 at 15 46 21" src="https://github.com/peviitor-ro/validator-ui/assets/103507535/f83776c5-24fe-4cbc-ad62-c919b1324a05">

**Comment by lalalaurentiu** [comment]
Added in pull request #94
