### ISSUE TITLE
a better responsive design for validator on the phone and a menu which could be closed.

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/validator-ui#45]
For a future feature - it would be nice if validator would be displayed in a responsive way when using on the phones.  At the moments, all the elements are not displayed correspondingly when acces validator on the phone (IOS system). See photos attached. 
Also, when i click on the menu it opens, but i cannot close it. It would be nice if the menu could be closed.

![WhatsApp Image 2024-05-13 at 20 28 44](https://github.com/peviitor-ro/validator-ui/assets/129604131/b4b97cd8-4c93-40da-9ab9-3b2a812abae9)
![WhatsApp Image 2024-05-13 at 20 28 43](https://github.com/peviitor-ro/validator-ui/assets/129604131/f4979861-5a22-4103-89ba-7eb5b9232363)

**Comment by lalalaurentiu** [comment]
Added...
