### ISSUE TITLE
Confirm Pop-up Yes / No for "Sterge" button

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/validator-ui#47]
ENVIRONMENT: production
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11 Pro

**DESCRIPTION:**

Introduce "Confirm Pop-up Yes / No" to avoid deleting a company by mistake. When you click on "Delete", a popup should appear that it  will have the role of validating the deletion option. It is necessary to avoid deleting it by mistake, especially for those who do not have access to add the company back.

**EXPECTED RESULTS:**
When you press the "Sterge" button, a confirm "Pop-up Yes / No" should appear for validating your choice.

**ACTUAL RESULTS:**
When you press the "Sterge" buttoun, the company is automatically deleted without being able to be added later if you do not have access.

<img width="188" alt="image" src="https://github.com/peviitor-ro/validator-ui/assets/23164347/b2438299-58d1-4672-a68e-e828c53ce9fb">

**Comment by lalalaurentiu** [comment]
Added in pull request #224
