### ISSUE TITLE
Verification of the search bar functionality with special characters ,, &&&&&&&&&

### ISSUE THREAD

**Issue by LucianLCI** [peviitor-ro/validator-ui#474]
Verify if the search bar functions with special characters ,, &&&&&&&&& ".
Preconditions: Have the https://admin.peviitor.ro/ page opened.

**Comment by Lore78** [comment]
>**Step 1**
1. Type in the search bar special characters like ,, &&&&&&&&& ".

**Expected results**
1. No companies should appear.
