### ISSUE TITLE
TC- search bar functionality with special characters

### ISSUE THREAD

**Issue by Georgiana95-ui** [peviitor-ro/validator-ui#477]
Description: search bar is functional with special characters ,, ###$$%%(( "
Preconditions: validator is open and running.

**Comment by Georgiana95-ui** [comment]
Step 1 : Login the validator.
Expected results : The homepage of the valiator is displayed.

**Comment by Georgiana95-ui** [comment]
Step 2:  enter special characters inside the search bar e.g "@,#$$"
Expected  result: the page after this query shoud be blank.
Actual result: the companies are still displayed.
<img width="958" alt="bug" src="https://github.com/user-attachments/assets/bf6a6fb1-39b6-4b2c-a2f0-d08d68d482b6">

**Comment by Georgiana95-ui** [comment]
ENVIROMENT: Testing and integration
URL: [peviitor.ro](https://peviitor.ro/)
Browser: Chrome
Device: Laptop
OS: Windows 10 

Precondition:
 validator is open and running

STEPS TO REPRODUCE:

Step 1 : Login the validator.
Expected results : The homepage of the valiator is displayed.

Step 2: enter special characters inside the search bar e.g "@,#$$"
Expected result: the page after this query shoud be blank.
Actual result: the companies are still displayed.
<img width="947" alt="bug" src="https://github.com/user-attachments/assets/72601f87-7102-44cb-9c1c-a77e5d78e365">

**Comment by lalalaurentiu** [comment]
Fixed..

**Comment by Georgiana95-ui** [comment]
retested.pass
