### ISSUE TITLE
Button "Editati" don't work and inserted values are not saved.

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#478]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter URL in browser
Go to "https://admin.peviitor.ro/" and check "Synevo"
Click on "Vizualizare joburi"
Click on "Editati"
In box "Localitati" insert Chiajna
From box "Tipul Jobului" select on-site 
Click on button "Editati" to save changes performed

EXPECTED RESULTS:
The page was save with inserted values. .

ACTUAL RESULTS:
After click on "Editati" page page is not saved and values accepted. Page don't work
See below screenshot.
![image](https://github.com/user-attachments/assets/d13394b8-99ff-4c2a-81e0-f93f622dd6a0)

**Comment by lalalaurentiu** [comment]
Asta a fost fixat în meet.
