### ISSUE TITLE
Number of Decathlon jobs in the validator does not correspond to the number of jobs in production

### ISSUE THREAD

**Issue by Lore78** [peviitor-ro/validator-ui#479]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open https://admin.peviitor.ro/
2. Click on "Companii" and check the total number of jobs for Decathlon.
3. Open https://peviitor.ro/
4. Click on the "Companie" filter and write "Decathlon" in the search bar.
5. Check if the total number of jobs in production corresponds to the total number of jobs in the validator.

**EXPECTED RESULTS:**
The total number of jobs in production corresponds to the total number of jobs in the validator.

**ACTUAL RESULTS:**
The total number of jobs in production does not correspond with the total number of jobs in the validator.

![image](https://github.com/user-attachments/assets/0162ab9b-e3d5-4408-b5ce-888ac1b5fca2)

![image](https://github.com/user-attachments/assets/971b7fd4-0e29-4a81-8f9a-513839dc9a12)

**Comment by lalalaurentiu** [comment]
Acela nu e numărul de joburi publicate în producție ci numărul de joburi aduse de scraper.
![IMG_0426](https://github.com/user-attachments/assets/142a4210-9f8b-4c7e-a62a-ae5befef1167)
![IMG_0427](https://github.com/user-attachments/assets/6ab36ff5-b359-4e9b-99a6-9ba913cda31b)

**Comment by Lore78** [comment]
Fixed
