### ISSUE TITLE
"Customer Service Analyst - Opera Cloud" job from Oracle is duplicated

### ISSUE THREAD

**Issue by Lore78** [peviitor-ro/validator-ui#481]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Click on "Companii".
2. Select "Oracle".
3. Click on "Vizualizeaza joburi".
4. Go to the "Customer Service Analyst - Opera Cloud" jobs and check their IDs.

**EXPECTED RESULTS:**
"Customer Service Analyst - Opera Cloud" jobs have different IDs.

**ACTUAL RESULTS:**
Two "Customer Service Analyst - Opera Cloud" jobs have the same ID 244691.

![image](https://github.com/user-attachments/assets/3e71f8fd-6b98-44b9-88cf-c86c28f0f7de)

**Comment by lalalaurentiu** [comment]
Jobul specificat de tine nu există în validator. Sunt 2 joburi cu același nume dar au “job idetification “ unice.
![IMG_0425](https://github.com/user-attachments/assets/268b9cd7-6a0c-4292-9be1-5f5aded1c4de)
![IMG_0424](https://github.com/user-attachments/assets/73afa534-f880-4826-a11a-06301b9a6e26)
