### ISSUE TITLE
The localities that contain at least two words in the validator, appear only with the first word in production

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/validator-ui#484]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL https://admin.peviitor.ro/ in the browser.
2. Click on any company.
3. Click on "Editati" from any job.
4. Put "Alba Iulia" in the "Localitatea" field.

**EXPECTED RESULTS:**
That job should appear in production for "Alba Iulia" city. 

**ACTUAL RESULTS:**
Only "Alba" appear for that job instead of "Alba Iulia".

![image](https://github.com/user-attachments/assets/968061ae-06c9-4972-aa28-27ad298ca0ac)

![image](https://github.com/user-attachments/assets/d04f9923-048e-4695-add7-ee449a37cd9d)

**Comment by lalalaurentiu** [comment]
Fixed...

**Comment by Florin201092** [comment]
FIXED!
