### ISSUE TITLE
Garrett - "Editati" button not functional on Safari

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/validator-ui#485]
ENVIRONMENT: Validator.ui
URL: URL: [Validator](hhttps://admin.peviitor.ro)
**Company_careers_url**: [Garrett](https://www.careers-page.com/ams-hr)
 Desktop:
```
OS: Sonoma 14.6.1
Browser: Safari
Version: 17.6
```

 
### **STEPS TO REPRODUCE:**
1) Type "Garrett" in the search field
2) Click on "Vizualizeaza Joburi" button
3) Scroll down to the "Indirect Site Buyer French" job listing
4) Click on "Editati" button
5) Select "hybrid" from the job type list
6) Click on "Editati" button

>**EXPECTED RESULTS:**
The new values are added to the job listing details.

>**ACTUAL RESULTS:**
The freshly inserted values are not being saved. 
The popup window will not close unless clicking on the "x" icon. 
Clicking the "x" icon does not save the new values.

>**ADDITIONAL INFO:**
This issue has been noticed on several **prepublished** job listings: Program Manager, Senior EDI Specialist.
"Stergeti" button does not work on the prepublished job listings.

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by iBixee** [comment]
Thank you!
