### ISSUE TITLE
HM - For the city of ”Targu Mures”, the county cannot be selected. Editing error

### ISSUE THREAD

**Issue by bogi1492** [peviitor-ro/validator-ui#49]
**ENVIRONMENT**: production
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE**:

1 .Open the URL in the browser
2. Click on the " Hm"
3. Open https://admin.peviitor.ro/jobs/Hm
4. Click on the "See Jobs" button.

**EXPECTED RESULTS**:
The company's job location is ”Targu Mures”, county ”Mures”.

**ACTUAL RESULTS**:
When you click on ”Editați” and what to write ”Targu Mures” in ”Localitatea” space, is no county to select for ”Targu Mures” city

**ATTACHEMENTS**:
![tm3](https://github.com/peviitor-ro/validator-ui/assets/142155043/55a29341-d8e1-44d6-8648-bb93800169ad)
![tm1](https://github.com/peviitor-ro/validator-ui/assets/142155043/cf2c909e-6ad6-477a-bcd6-3ab4556a4d32)
![tm2](https://github.com/peviitor-ro/validator-ui/assets/142155043/cc7ca218-0d7d-43a1-ba60-1b336fc53676)

**Comment by lalalaurentiu** [comment]
![image](https://github.com/peviitor-ro/validator-ui/assets/67306273/30a65b0c-8e7f-4ba3-9130-d39e0f3053f1) it's Targu-Mures
