### ISSUE TITLE
Check the spelling of the "desc." option in the sort dropdown menu

### ISSUE THREAD

**Issue by Lore78** [peviitor-ro/validator-ui#496]
Description: Check that the "desc." options in the sort dropdown menu from the "Companii" section are all written either Sentence case or Lower case.
Preconditions: Have the https://admin.peviitor.ro/ page opened.

**Comment by SimonaNemtanu** [comment]
@Lore78 Missing steps. Please review and complete.

**Comment by Lore78** [comment]
**Steps to reproduce**:
Check that the "desc." option in the sort dropdown menu are all written either Sentence case or Lower case.

**Expected results**:
The "desc." option in the sort dropdown menu are all written either Sentence case or Lower case.
