### ISSUE TITLE
HM - For the city of ”Piatra Neamt”, the county cannot be selected. Editing error

### ISSUE THREAD

**Issue by bogi1492** [peviitor-ro/validator-ui#50]
**ENVIRONMENT**: production
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE**:

1 .Open the URL in the browser
2. Click on the " Hm"
3. Open https://admin.peviitor.ro/jobs/Hm
4. Click on the "See Jobs" button.

**EXPECTED RESULTS**:
The company's job location is ”Piatra Neamt”, county ”Neamt”.

**ACTUAL RESULTS**:
When you click on ”Editați” and what to write ”Piatra Neamt” in ”Localitatea” space, is no county to select for ”Piatra Neamt” city

**ATTACHEMENTS**:

![pn2](https://github.com/peviitor-ro/validator-ui/assets/142155043/d9a1ecd6-a9be-4fb8-a861-a03fa57acf2e)
![pn1](https://github.com/peviitor-ro/validator-ui/assets/142155043/e62856e8-b7dc-41c6-847c-1fdb5a768aa8)

**Comment by lalalaurentiu** [comment]
![image](https://github.com/peviitor-ro/validator-ui/assets/67306273/6a775661-38c2-45c3-a157-3749f1428771) it's Piatra-Neamt
