### ISSUE TITLE
TC Dropdown "Personale Nr. joburi nepublicate" is displayed

### ISSUE THREAD

**Issue by RoxanaDanalache** [peviitor-ro/validator-ui#507]
Description: Verify that the dropdown option  "Personale Nr. joburi nepublicate", from the "Companii" page, is displayed.
Preconditions: Go to: https://admin.peviitor.ro/

**Comment by RoxanaDanalache** [comment]
Step 1: Navigate to the "Companii" page.
Expected result: The "Companii" page is available.

**Comment by RoxanaDanalache** [comment]
Step 2: Click on the dropdown component.
Expected result: The option is selectable.

**Comment by RoxanaDanalache** [comment]
Step 3: Verify if the dropdown expands and reveals the option "Personale Nr. joburi nepublicate".
Expected result: The dropdown expands showing the option "Personale Nr. joburi nepublicate".

**Comment by RaduLutu** [comment]
TC Dropdown "Personale Nr. joburi nepublicate" is displayed ✅
