### ISSUE TITLE
TC Dropdown "Personale Nr. joburi nepublicate" functionality

### ISSUE THREAD

**Issue by RoxanaDanalache** [peviitor-ro/validator-ui#508]
Description: Verify if selecting "Personale Nr. joburi nepublicate" from the dropdown list, leads to a specific page.
Preconditions: Go to https://admin.peviitor.ro/

**Comment by RoxanaDanalache** [comment]
Step 1: Navigate to the "Companii" page.
Expected result: The "Companii" page is available.

**Comment by RoxanaDanalache** [comment]
Step 2: Click on the dropdown component.
Expected result: The option is selectable.

**Comment by RoxanaDanalache** [comment]
Step 3: Verify if clicking on the "Personale Nr. joburi nepublicate" option is leading to a page with a list of companies.
Expected result: The list of companies is shown.

**Comment by RaduLutu** [comment]
TC Dropdown "Personale Nr. joburi nepublicate" functions ✅
