### ISSUE TITLE
HICX- Job no longer available

### ISSUE THREAD

**Issue by bogi1492** [peviitor-ro/validator-ui#51]
**ENVIRONMENT**: production
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE**:

1 .Open the URL in the browser
2. Click on the " HICX"
3. Open https://admin.peviitor.ro/jobs/Hicx
4. Click on the "See Jobs" button.

**EXPECTED RESULTS**:
When you click on ”Catre Job” the page will redirect you to official job website of the company, where you can find all the details about the job.

**ACTUAL RESULTS**:
When you click on ”Catre Job” you will be redirected to the job website but on the page is an error that says the job is no longer available.

**ATTACHEMENTS**:

![hicx](https://github.com/peviitor-ro/validator-ui/assets/142155043/56b03442-a660-48a5-8b74-50c7454d5c22)
![hicx2](https://github.com/peviitor-ro/validator-ui/assets/142155043/0fbf28e2-8a35-42cc-ad08-75c2a16d65fe)

**Comment by lalalaurentiu** [comment]
Scraperul este nefunctional din data de 16 mai deoarece compania nu mai are posturi disponibile in Romania.
<img width="1440" alt="Screenshot 2024-05-29 at 12 22 48" src="https://github.com/peviitor-ro/validator-ui/assets/67306273/5296db5a-8c53-4651-ba12-4b1d9a41c2ff">
Se recomanda stergerea manuala a jobului.
