### ISSUE TITLE
Danieli - "Stergeti" button not functional

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/validator-ui#516]
ENVIRONMENT: Validator.ui
URL: URL: [Validator](hhttps://admin.peviitor.ro)
**Company_careers_url**: [Danieli](https://admin.peviitor.ro/jobs/danieli)

 Desktop:
```
OS: Sonoma 14.6.1
Browser: Chrome
Version: 129
```

### **STEPS TO REPRODUCE:**
1) Type "Danieli" in the search field.
2) Click on "Vizualizeaza Joburi".
4) Click on "Stergeti" button on the job listing card.

>**EXPECTED RESULTS:**
Job listing is deleted from the list.

>**ACTUAL RESULTS:**
Clicking the "Stergeti" button does not delete the job listing. 
Job remains active in the list and in production.

**Comment by lalalaurentiu** [comment]
Fixed...
