### ISSUE TITLE
Colgate - "Editati" and "Stergeti" buttons not functional

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/validator-ui#517]
ENVIRONMENT: Validator.ui
URL: URL: [Validator](hhttps://admin.peviitor.ro)
**Company_careers_url**: [Colgate](https://admin.peviitor.ro/jobs/Colgate)
 Desktop:
```
OS: Sonoma 14.6.1
Browser: Chrome
Version: 129
```

 
### **STEPS TO REPRODUCE:**
1) Type "Colgate" in the search field
2) Click on "Vizualizeaza Joburi" button
3) Navigate to "Pharma&Prof Territory Exec" job listing
4) Click on "Editati" button
5) Select "hybrid" from the job type list
6) Click on "Editati" button
7) Click on the "x" icon to close the popup window
8) Click on "Stergeti" button

>**EXPECTED RESULTS:**
The new values are added to the job listing details.
Job listing is deleted from the list.

>**ACTUAL RESULTS:**
The freshly inserted values are not being saved. 
The popup window will not close unless clicking on the "x" icon. 
Clicking the "x" icon does not save the new values.
Clicking the "Stergeti" button does not delete the job listing.
Job remains active in the list and in production.

>**ADDITIONAL INFO:**
"Editati" and "Stergeti" buttons does not work on some published job listings.

**Comment by lalalaurentiu** [comment]
Fixed..
