### ISSUE TITLE
The cursor remains at the bottom of the page when you click on "Vizualizeaza joburi" button

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/validator-ui#519]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Scroll down
3. Click on "Vizualizeaza joburi" button from any company

**EXPECTED RESULTS:**
The cursor should stay at the top of the page.

**ACTUAL RESULTS:**
The cursor remains at the bottom of the page

https://github.com/user-attachments/assets/4a60b0f6-fa81-4286-b36c-4ea3537640c5

**Comment by lalalaurentiu** [comment]
Fixed...

**Comment by Florin201092** [comment]
fixed
