### ISSUE TITLE
Antal - Covasna is not a city

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/validator-ui#52]
ENVIROMENT: ui.validator
URL: [Antal-Validator UI](https://admin.peviitor.ro/jobs/Antal)
 Desktop:
```
OS: MacOS
Browser: Chrome
```
### **STEPS TO REPRODUCE:**
1) Click on "Companii"
2) Click in the "Cauta aici..." search bar.
3) Write "Antal"
4) Click on "Vizualizeaza joburi"
5) Scroll-down to "Reprezentant medical – Zona Transilvania"

>**EXPECTED RESULTS:**
The job description of the position "Reprezentant medical – Zona Transilvania" is located in Covasna county

>**ACTUAL RESULTS:**
The link does not correspond to the "Reprezentant medical – Zona Transilvania" is located in City Covasna, County Covasna. **!!Covasna is not a city!!**

<img width="479" alt="Screenshot at May 20 14-45-25" src="https://github.com/peviitor-ro/validator-ui/assets/137428958/d1124e42-e67a-4dea-ad4a-b79f0504077a">

**Comment by lalalaurentiu** [comment]
Există și localitatea Covasna [link](https://ro.m.wikipedia.org/wiki/Covasna)
[linkul Primăriei](https://www.primariacovasna.ro/home/)
