### ISSUE TITLE
Chart from scraper for Valeo doesn't work !

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#522]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter URL in browser
Go to "https://admin.peviitor.ro/" and check "Valeo"
Click on "Vizualizare joburi"
Check diagram / graphic for run of scraper

EXPECTED RESULTS:
Diagram show scraper work for curent day.

ACTUAL RESULTS:
Scraper don't work from 18 September 2024 - see below screenshot:

![image](https://github.com/user-attachments/assets/fc617821-eedd-4066-8e9e-d0990139e718)

**Comment by lalalaurentiu** [comment]
Fixed...
