### ISSUE TITLE
Valeo scraper not exist in DataBase for scrapers

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#523]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter URL in browser
Go to "https://admin.peviitor.ro/" and check "Cont" from top bar
Click on "Scraperi"
Click on "Actualizeaza" button
Click on figure "based_scraper_py" pictures
Check VALEO scraper

EXPECTED RESULTS:
VALEO scraper exist in DataBase .

ACTUAL RESULTS:
Scraper don't exist in DataBase - see below screenshot:

![image](https://github.com/user-attachments/assets/2efd8cb9-2b22-4344-ac90-4144015b0ecf)

**Comment by Cristian-Emil** [comment]
Solved. After I press 3 time button "Actualizeaza" and charge 3 time "Scrapy_peviitor_jobs", DB was correct charged. 
Need to check whay, from time to time, have this behavior / malfunction.
( Can be a bad connection or missing file from DB ).

**Comment by andreireporter13** [comment]
Pai da, dar eu sunt scraperist. :))
Pentru reparare baze de date, va rog, in biroul celalalt. :))) Gluma.

Laurentiu zicea ca mai apar erori. Ba ca se mai ruleaza ceva, ba ca nu sunt
updatate datele in aplicatie. Etc.

În lun., 30 sept. 2024 la 22:01, Cristian Zidarescu <
***@***.***> a scris:

**Comment by lalalaurentiu** [comment]
Nu cauți unde trebuie , Valeo e în repozitoriul lui @andreireporter13  cu scrapy ![image](https://github.com/user-attachments/assets/4bc9ad52-548a-45d4-b176-7dae9a279866)
