### ISSUE TITLE
The status doesn't change when you run manually another scraper

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/validator-ui#528]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser;
2. Click on "Scraperi" and open the "JobsScrapers" folder;
3. Search for "Orange" scraper;
4. Run the "Orange" scraper;
5. At this moment, there is an error when you run this scraper so the status is "Eroare";
6. Paste "Nokia" on the search field.

**EXPECTED RESULTS:**
The status should change to "Ruleaza".

**ACTUAL RESULTS:**
The status still remained "Eroare".

https://github.com/user-attachments/assets/c7980ecd-e2f9-4445-a45f-433f688bc440

**Comment by lalalaurentiu** [comment]
Modul de afisare al bugurilor sa schimbat asa ca bugul nu se mai poate reproduce.
