### ISSUE TITLE
Antal - "Jucu" does not appear in the drop-down menu

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/validator-ui#53]
ENVIROMENT: ui.validator
URL: [Antal-Validator UI](https://admin.peviitor.ro/jobs/Antal)
 Desktop:
```
OS: MacOS
Browser: Chrome
```
### **STEPS TO REPRODUCE:**
1) Click on "Companii"
2) Click in the "Cauta aici..." search bar.
3) Write "Antal"
4) Click on "Vizualizeaza joburi"
5) Scroll-down to "Parametric Design Engineer - hybrid, Jucu"
6) Click "Editati"
7) Press "X" button to erase the location from "Localitatea" field
8) Click on the serch field from "Localitatea"
9) Write "Jucu"

>**EXPECTED RESULTS:**
"Jucu" appears in the drop-down menu

>**ACTUAL RESULTS:**
"Jucu" does not appear in the drop-down menu

https://github.com/peviitor-ro/validator-ui/assets/137428958/3ff4952f-429b-4abe-9794-e3d7289af46c

**Comment by lalalaurentiu** [comment]
Fixed
