### ISSUE TITLE
Betfair scraper doesn't work. Warning sign appear!

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#544]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter URL in browser
Go to "https://admin.peviitor.ro/" and check "Cont" from top bar
Click on "Scraperi"
Click on "Actualizeaza" button
Click on figure/picture "based_scraper_py"
Check BETFAIR scraper
Click on BETFAIR scraper

EXPECTED RESULTS:
BETFAIR scraper must to run .

ACTUAL RESULTS:
Scraper doesn't work. Warning sign appear - see below screenshot:

![image](https://github.com/user-attachments/assets/d57c4e4f-1942-445b-9137-3355676740ac)

**Comment by lalalaurentiu** [comment]
Scraperul a rulat ...![image](https://github.com/user-attachments/assets/7cf3d697-00d2-465e-a160-d8c8bacbf042) 
![image](https://github.com/user-attachments/assets/8990e034-f7a6-42f2-b7f0-af03aa1fd7f0)
