### ISSUE TITLE
"Freudenberg" - Duplicated Company

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/validator-ui#547]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Search for company "Freudenberg"

**EXPECTED RESULTS:**
Only one company should appear.

**ACTUAL RESULTS:**
Two companies appear.

![image](https://github.com/user-attachments/assets/5bfd0634-212f-47f9-9e3a-fe9055a9ce17)

**Comment by lalalaurentiu** [comment]
Fixed… a fost ștearsă din based_scraper_py

**Comment by Florin201092** [comment]
Fixed
