### ISSUE TITLE
"Ștergeți" Button Non-functional on Job Listing Cards

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/validator-ui#551]
Testers are unable to remove job listings that are no longer available, leading to inefficiency in the validation process. This disrupts the workflow and causes confusion when trying to manage invalid listings and remain visible on peviitor.ro.

**Proposed Enhancement:** Implement functionality for the "Stergeti" button so that it allows testers to delete invalid or unavailable job listings after validation. Ensure that the deletion process does not refresh the page, and instead removes the listing from the UI dynamically, preserving the tester’s current position on the page.

ENVIRONMENT: Validator.ui
URL: URL: [Validator](hhttps://admin.peviitor.ro)
**Company_careers_url**: [Qiagen](https://admin.peviitor.ro/jobs/Qiagen)
 Desktop:
```
OS: Sonoma 14.6.1
Browser: Chrome
Version: 129
```

### **STEPS TO REPRODUCE:**
1) Type "Qiagen" in the search field.
2) Click on "Vizualizeaza Joburi".
3) Navigate to the "**QDI Senior Web Developer**" position.
4) Click on "Catre Job" and observe the current status of the job listing.
5) Return on the validator page and locate the "Stergeti" button on the job listing card.
6) Click the "Stergeti" button.
7) Observe that no action is performed after clicking the button.

>**EXPECTED RESULTS:**
The "Stergeti" button should allow testers to delete the job listing from the system once it is validated as unavailable. Upon clicking the button, the listing should be removed from the database and the UI without refreshing the entire page.

>**ACTUAL RESULTS:**
The "Stergeti" button is present but non-functional. Clicking the button does not perform any action, and the job listing remains on the page.

_**Additional Information:**
This issue occurs across multiple browsers, including Safari and Chrome._

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by iBixee** [comment]
Thank you!
