### ISSUE TITLE
Company Job Listing Page Search Bar Stops Accepting Input After Typing One Letter

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/validator-ui#552]
ENVIRONMENT: Validator.ui
URL: URL: [Validator](hhttps://admin.peviitor.ro)

 Desktop:
```
OS: Sonoma 14.6.1
Browser: Chrome
Version: 129
```

### **STEPS TO REPRODUCE:**
1) Navigate to any company page.
2) Click inside the search bar.
3) Start typing a word, one letter at a time.
4) Observe that after typing one letter, the results are immediately returned, and the search bar loses focus.
5) Click on the search bar again to continue typing.
6) Type one more letter: results are returned again, and the search bar loses focus.

**Alternate scenario:**
1) Try to type a whole word without pausing.
2) Notice that if you stop typing for a brief moment, the results are immediately returned, and the search bar loses focus.

>**EXPECTED RESULTS:**
The user should be able to continuously type in the search bar without interruptions, regardless of how fast or slow they are typing. The search results should only be returned after the tester has finished typing or clicks a "Search" button. The input field should not lose focus while the tester is still typing.

>**ACTUAL RESULTS:**
After typing a single letter, the search results are immediately returned, and the search bar loses focus, preventing the tester from continuing to type without clicking back into the search bar. If the tester attempts to write a full word uninterrupted, the search works. However, if they pause for even a second, the results are returned prematurely, stopping further input. It is difficult to input two or more words into the search bar due to these interruptions.

**Proposed Enhancement/Fix:** 
 - Implement a delay before search results are triggered after typing, allowing the tester to complete their input without the search field losing focus.
 - Ensure that the search bar maintains focus while the tester is typing.
 - Optionally, add a "Cautati" button that testers can click after completing their search term, or allow for a more user/tester-friendly debounce time (ex: results return 500ms or 1 second after the last keystroke).

**Additional Information:**
This issue occurs across multiple browsers, including Chrome and Safari.

**Comment by lalalaurentiu** [comment]
Fixez...
Căutarea nu se mai face automat ci după apăsarea butonului caută sau tastei enter
