### ISSUE TITLE
Edit activity return error message for Platform Engineer - Flutter UK&I, Hybrid from Betfair company

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#554]
ENVIRONMENT:
https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter URL in browser
Go to "https://admin.peviitor.ro/" and check on search box "Cauta aici ..."
Insert in box "Betfair"
Press ENTER.
Go to icone "Betfair" and press on button "Vizualizeaza joburi"
On"Betfair" page check job "Platform Engineer - Flutter UK&I, Hybrid" click on button "Editeaza"
Select all the correct option and press "Editati"

EXPECTED RESULTS:
Job for "Platform Engineer - Flutter UK&I, Hybrid" must to be saved with correct value.

ACTUAL RESULTS:
Page for "Platform Engineer - Flutter UK&I, Hybrid"return error message and don't load available values.
"Error! A aparut o eroare." - see below screenshot:

![image](https://github.com/user-attachments/assets/0da47d73-dde5-47a7-84cf-24b739b18e1a)

**Comment by lalalaurentiu** [comment]
Fixed
