### ISSUE TITLE
Graphic for Betfair scraper are not running!

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#555]
ENVIRONMENT:
https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter URL in browser
Go to "https://admin.peviitor.ro/" and check on search box "Cauta aici ..."
Insert in box "Betfair"
Press ENTER.
Go to icone "Betfair" and press on button "Vizualizeaza joburi"
On"Betfair" page check graphic for running scraper.

EXPECTED RESULTS:
Scraper graphic for Betfair must to be up-date. 

ACTUAL RESULTS:
Graphic show screpr is not running from 14.10. - see below screenshot:

![image](https://github.com/user-attachments/assets/360a6f35-43dd-48b5-b016-8dbc85513245)

**Comment by lalalaurentiu** [comment]
fixed
