### ISSUE TITLE
The search function is not working on "Scraperi" page

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/validator-ui#558]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2.Click on "Scraperi" button
3. Open any folder from the "Scraperi" page
4. Try to search any scraper

**EXPECTED RESULTS:**
The search function should work.

**ACTUAL RESULTS:**
The search function is not working.

![image](https://github.com/user-attachments/assets/ca32b811-a80d-4b1b-8d24-5acd74ff3ee8)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by Florin201092** [comment]
Fixed
