### ISSUE TITLE
"AIRBUS" company - the logo is not visible

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/validator-ui#559]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Search for "AIRBUS" company
3. Observe the logo.

**EXPECTED RESULTS:**
The logo should be visible and easy to understand.

**ACTUAL RESULTS:**
The logo is not visible.

![image](https://github.com/user-attachments/assets/a808a26a-457f-4fbb-b6f8-7122cb8dfaab)

**Comment by lalalaurentiu** [comment]
Fixed...

**Comment by Florin201092** [comment]
fixed
