### ISSUE TITLE
"Intesasanpaolobank" - Duplicated Company 

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/validator-ui#56]
URL: https://peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Click on the "Cauta" button
3. Click on the "Companie" button and write "Intesasanpaolobank" in the search bar.

**EXPECTED RESULTS:**
When you write "Intesasanpaolobank" in the search bar, the user should be able to see only one option.

**ACTUAL RESULTS:**
When you write "Intesasanpaolobank" in the search bar, two identical options appear.

<img width="181" alt="image" src="https://github.com/peviitor-ro/validator-ui/assets/23164347/f247aa86-b19e-472a-bce3-5b13bc3aba60">

**Comment by lalalaurentiu** [comment]
Fixed
