### ISSUE TITLE
You can publish the same job several times in production

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/validator-ui#561]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser.
2. Search for "Leohr" company.
3. Click on "Vizualizeaza joburi".
4. Publish any job.
5. Publish again the same job.

**EXPECTED RESULTS:**
A job should be published only once.

**ACTUAL RESULTS:**
The same job can be published several times.

https://github.com/user-attachments/assets/143a80ef-8fb5-4e04-8156-f761fb47e685

**Comment by lalalaurentiu** [comment]
Fixed
