### ISSUE TITLE
The menu is slowly when the company has many jobs

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/validator-ui#562]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser.
2. Search for "Prohuman" company.
3. Click on "Vizualizeaza joburi".
4. Observe how the menu is working

**EXPECTED RESULTS:**
The menu should run without issues and lag.

**ACTUAL RESULTS:**
The menu has lag.

https://github.com/user-attachments/assets/12ea3ae3-4ef0-4414-8811-41e135bb3a5f

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by Florin201092** [comment]
Fixed
