### ISSUE TITLE
The cursor disappears when you search for a job

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/validator-ui#563]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser.
2. Search for "Prohuman" company.
3. Click on "Vizualizeaza joburi".
4. Search for "russian" 

**EXPECTED RESULTS:**
The search field should be active.

**ACTUAL RESULTS:**
The search field is not active.

https://github.com/user-attachments/assets/7f3dd3c7-20ad-485b-b367-6b0eebc25d5f

**Comment by lalalaurentiu** [comment]
Fixed...
Cautarea nu se mai face automat ci dupa apasarea butonului cauta sau apasarea tastei enter
