### ISSUE TITLE
Job from Signicant is out of line/data!

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#564]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter URL in browser
Go to "https://admin.peviitor.ro/" and check "Signicant" 
Click on "Vizualizeaza Joburi"
Go to job "Senior Platform Engineer - Romania" and click on page to activate bottom bar with options
Press on button  "Vizualizeaza Jobul" 

EXPECTED RESULTS:
"Senior Platform Engineer - Romania" must to display valid page .

ACTUAL RESULTS:
Page is out of data , job invalid  - see below screenshot:

![image](https://github.com/user-attachments/assets/0b601372-ca49-4f63-8f84-dc17dd43cd7e)

**Comment by lalalaurentiu** [comment]
Compania nu mai e in validator....
<img width="1440" alt="Screenshot 2024-12-17 at 19 06 45" src="https://github.com/user-attachments/assets/9d0f13f1-9fc3-44e8-901f-54ef8168fe01" />
