### ISSUE TITLE
"Jacobsdouweegberts" - Duplicated Company

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/validator-ui#57]
URL: https://peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Click on the "Cauta" button
3. Click on the "Companie" button and write "Jacobsdouweegberts" in the search bar.

**EXPECTED RESULTS:**
When you write "Jacobsdouweegberts" in the search bar, the user should be able to see only one option.

**ACTUAL RESULTS:**
When you write "Jacobsdouweegberts" in the search bar, two identical options appear.

<img width="261" alt="image" src="https://github.com/peviitor-ro/validator-ui/assets/23164347/7c42b2e8-c2a1-4521-976a-be15faf8875b">

**Comment by lalalaurentiu** [comment]
Fixed 
<img width="1440" alt="Screenshot 2024-06-19 at 14 21 54" src="https://github.com/peviitor-ro/validator-ui/assets/67306273/90e80721-48f5-413c-8c55-9194bb29cfc2">
