### ISSUE TITLE
Add a color for the jobs companies menu

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/validator-ui#570]
To be seen easier, it would be nice if the menu for the jobs of the companies would have a color..like the "Cauta" button from peviitor.ro for example . (rgb(4 138 129))

Thanks

**Comment by lalalaurentiu** [comment]
@DeedeeDL ce zici de ceva in genul acesta?
<img width="408" alt="Screenshot 2024-11-16 at 22 55 29" src="https://github.com/user-attachments/assets/08bc1e02-5f29-49a9-af75-c3117a3cdf7a">

**Comment by lalalaurentiu** [comment]
Added

**Comment by DeedeeDL** [comment]
Suuuper ! agreed ! Thank you Laur !
