### ISSUE TITLE
In production the job display incorrect

### ISSUE THREAD

**Issue by talmacelanamaria** [peviitor-ro/validator-ui#571]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser.
2.Search for "OSF digital" company.
3.Click on "Vizualizeaza joburi".
4.Search for "QA Expert in Marketing cloud"

EXPECTED RESULTS:
The job appears correct about city and way of working after edit on validator

ACTUAL RESULTS:
In production the job display incorrect

![Captură de ecran 2024-10-24 140415](https://github.com/user-attachments/assets/b5f4bf6f-88ab-4d1d-94be-f06f22d59275)

<img width="167" alt="image" src="https://github.com/user-attachments/assets/a433c977-b8e4-4861-88b7-e2f4fcad5305">

**Comment by lalalaurentiu** [comment]
Fixed 
<img width="1440" alt="Screenshot 2024-12-15 at 02 27 22" src="https://github.com/user-attachments/assets/2c1344a8-1383-4c77-81d7-bea44c6d6434" />

**Comment by talmacelanamaria** [comment]
Closed
