### ISSUE TITLE
Job can't be erased in validator

### ISSUE THREAD

**Issue by mihaelaadam** [peviitor-ro/validator-ui#576]
ENVIROMENT: validator UI
URL: https://peviitor.ro/
**Company_careers_url**: [Astormueller](https://admin.peviitor.ro/jobs/Astormueller)
 Desktop:
```
OS: Windows 11
Browser: Chrome
Version: 130.0.6723.70
```

 
### **STEPS TO REPRODUCE:**
1) click on job card "Controller (f/m/d)"
2) click on "Sterge" icon

>**EXPECTED RESULTS:**
1) job is deleted from the list and is not visibile on the page

>**ACTUAL RESULTS:**
1) page returns an error
2) job is not deleted
<br>

**Screenshots**
...
![chrome_7yQbpln8tZ](https://github.com/user-attachments/assets/6677228c-393b-468e-ab87-ca3a1d9eb503)

**Comment by lalalaurentiu** [comment]
fixed
