### ISSUE TITLE
Duplication for job from "Strabag" is impossible to delete

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#582]
ENVIRONMENT:
https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Enter URL in browser
Go to "https://admin.peviitor.ro/" and check on search box "Cauta aici ..."
Insert in box "STRABAG" and press ENTER.
Go to icone "STRABAG" and press on button "Vizualizeaza joburi"
On "STRABAG" page open job "Expert proiectare poduri" using icon "Vizualizeaza Jobul".

EXPECTED RESULTS:
Jobs from "STRABAG" for "Expert proiectare poduri" must to on display valid page.
This page can be deleted if request (in case of duplication).

ACTUAL RESULTS:
Are displayed 2 identic pages for job "Expert proiectare poduri". When try to delete one joib from page we are received error message - see below screenshots:

![image](https://github.com/user-attachments/assets/4966863e-8707-484d-b4b5-0a8ae22bd0eb)

![image](https://github.com/user-attachments/assets/e45c5fd4-4c92-4d16-abb6-7b6173bfc7dd)

**Comment by lalalaurentiu** [comment]
fixed
