### ISSUE TITLE
Company name  too long for "infotreeglobalsolutions" causes misalignment 

### ISSUE THREAD

**Issue by Lore78** [peviitor-ro/validator-ui#586]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

Preconditions:
Have the https://admin.peviitor.ro/ page opened.

STEPS TO REPRODUCE:
1) Click on "Scraperi".
2) Search for "infotreeglobalsolutions.py".
3) Run the "infotreeglobalsolutions.py" scraper. 

EXPECTED RESULTS:
The message "Se ruleaza scraperul infotreeglobalsolutions.py" should be properly aligned in the center.

ACTUAL RESULTS:
The message "Se ruleaza scraperul infotreeglobalsolutions.py" is aligned at the left with a tendency of leaving the frame. 

![image](https://github.com/user-attachments/assets/43f8fd14-63dc-4145-9375-266586aec06d)

**Comment by lalalaurentiu** [comment]
in ce repozitoriu se afla scraperul?

**Comment by Lore78** [comment]
Scrapers Python iurie

**Comment by lalalaurentiu** [comment]
Fixed..

**Comment by Lore78** [comment]
Fixed and center aligned 
![image](https://github.com/user-attachments/assets/80ea4d79-1734-491e-8206-772bd261271a)
