### ISSUE TITLE
HP - Job link is not working

### ISSUE THREAD

**Issue by bogi1492** [peviitor-ro/validator-ui#59]
**ENVIRONMENT**: production
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE**:

1 .Open the URL in the browser
2. Click on the " HP"
3. Open https://admin.peviitor.ro/jobs/Hp
4. Click on the "See Jobs" button.

**EXPECTED RESULTS**:
When you click on ”Catre Job” the page will redirect you to official job website of the company, where you can find all the details about the job.

**ACTUAL RESULTS**:
When you click on ”Catre Job” an error pops and says that ”Page not found”.

**ATTACHEMENTS**:
![hperr1](https://github.com/peviitor-ro/validator-ui/assets/142155043/66b084d3-aa75-4af4-a106-c1f606a3fa2b)
![hperr1](https://github.com/peviitor-ro/validator-ui/assets/142155043/66b084d3-aa75-4af4-a106-c1f606a3fa2b)
![hperr](https://github.com/peviitor-ro/validator-ui/assets/142155043/dd73de81-1f06-4b93-805b-fe137ff5f94b)
![hperr](https://github.com/peviitor-ro/validator-ui/assets/142155043/dd73de81-1f06-4b93-805b-fe137ff5f94b)

**Comment by lalalaurentiu** [comment]
Fixed
