### ISSUE TITLE
"Zenitech" scraper is not working

### ISSUE THREAD

**Issue by RaduLutu** [peviitor-ro/validator-ui#596]
URL: https://admin.peviitor.ro/
Browser: Microsoft Edge
Device: Desktop
OS: Windows 11

STEPS TO REPRODUCE:

Open the URL in the browser.
Click on "Scraperi".
Click on "scrapers_python_iurie" folder.
Run the "zenitech.py" file.

EXPECTED RESULTS:
The scraper should run without issues.
ACTUAL RESULTS:
The scraper displays an error message.
![Screenshot 2024-11-12 134619](https://github.com/user-attachments/assets/4b15ba98-0dfa-412b-ab84-73765910bdf9)

**Comment by Florin201092** [comment]
![image](https://github.com/user-attachments/assets/97482fd7-049f-47dd-b02b-c7a48db447ed)

https://zenitech.co.uk/careers/romania/

**Comment by IurieChi** [comment]
fixed Zenitech bug #596
