### ISSUE TITLE
Drop-down menu for "Toate" section

### ISSUE THREAD

**Issue by yonutzu** [peviitor-ro/validator-ui#60]
ENVIRONMENT: production
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: PC
OS: Windows 11 PRO

STEPS TO REPRODUCE:
1 Open the URL in the browser and connect to user.
2. On the page "Companii" type in the searching bar the company you wish to review, for example CBS and enter
3. Click the button "Viuzualizeaza joburi"
4. After you have the jobs displayed, go to one of the jobs and click the drop-down menu "Toate"
5. See the text option "Neditate" 

EXPECTED RESULTS:
The text-option should be "Needitate" in drop down menu "Toate"

ACTUAL RESULTS:
The text-option is "Neditate" is write wrong  in drop down menu "Toate"

![Neditate](https://github.com/peviitor-ro/validator-ui/assets/76839121/851e8529-33d1-4ae0-84d7-3d67fb0727da)

**Comment by lalalaurentiu** [comment]
Fixed
