### ISSUE TITLE
Job is duplicate and error appear when try to validate in AUCHAN page!

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#604]
ENVIRONMENT:
https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
1. enter URL in browser
2. go to "https://admin.peviitor.ro/" and check on search box "Cauta aici ..."
3. insert in box "Auchan"
4. Press ENTER.
5. go to icone "Auchan" and press on button "Vizualizeaza joburi"
6. on "Auchan" page check job "Operator polivalent Brutarier" click on button "Vizualizeaza jobul"

EXPECTED RESULTS:
Job for "Operator polivalent Brutarie" must to be valid.

ACTUAL RESULTS:
Job for "Operator polivalent Brutarie" is duplicate and error appear when try to validate.
See below screenshot:

![image](https://github.com/user-attachments/assets/13238d74-5303-4e6e-90e6-ba65b6c8c8cc)

![image](https://github.com/user-attachments/assets/9a69b96d-b55a-421c-afe9-b28af22b1807)

**Comment by lalalaurentiu** [comment]
Fixed
