### ISSUE TITLE
Error message appear when try to validate job in Betfair page!

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#605]
ENVIRONMENT:
https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
1. enter URL in browser
2. go to "https://admin.peviitor.ro/" and check on search box "Cauta aici ..."
3. insert in box "Betfair" and press ENTER.
4. go to icone "Betfair" and press on button "Vizualizeaza joburi"
5. on "Betfair" page check job "Internship Data Engineer - Flutter UK&I, Hybrid" click on button "Editeaza"
6. go on job icon and after press "Editeaza""
7. checke/ confirm location and type of job, press button "Editati"

EXPECTED RESULTS:
Job for  "Internship Data Engineer - Flutter UK&I, Hybrid" must to save new valuez inserted.

ACTUAL RESULTS:
On job for "Operator polivalent Brutarie" error mesasge appear when try to validate.
See below screenshot:

![image](https://github.com/user-attachments/assets/05578753-b3ea-4e31-a6af-1cb162ac3f81)

**Comment by lalalaurentiu** [comment]
fixed
