### ISSUE TITLE
Job  "Internship Data Engineer - Flutter UK&I, Hybrid" is duplicate in BETFAIR page!

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#606]
ENVIRONMENT:
https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. enter URL in browser
2. go to "https://admin.peviitor.ro/" and check on search box "Cauta aici ..."
3. insert in box "Betfair" and press ENTER.
4. go to icone "Betfair" and press on button "Vizualizeaza joburi"
5. on "Betfair" page check job "Internship Data Engineer - Flutter UK&I, Hybrid" click on button "Vizualizeaza jobul"
6. go on job icon and after press "Editeaza""
7. checke/ confirm location and type of job, press button "Editati"

EXPECTED RESULTS:
Job for "Internship Data Engineer - Flutter UK&I, Hybrid" must to be valid.

ACTUAL RESULTS:
Job for "Internship Data Engineer - Flutter UK&I, Hybrid" is duplicate and error appear when try to validate.
See below screenshot:

https://www.betfairromania.ro/jobs/jr123525/internship-data-engineer-flutter-uki-hybrid/

![image](https://github.com/user-attachments/assets/7a6616f2-0607-490d-8947-57a621af30f2)

**Comment by lalalaurentiu** [comment]
Fixed
