### ISSUE TITLE
Job "Workplace Engineer - Flutter Group, Hybrid & Remote" is duplicate in BETFAIR page!

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#608]
ENVIRONMENT:
https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
1. enter URL in browser
2. go to "https://admin.peviitor.ro/" and check on search box "Cauta aici ..."
3. insert in box "Betfair" and press ENTER.
4. go to icone "Betfair" and press on button "Vizualizeaza joburi"
5. on "Betfair" page check job "Workplace Engineer - Flutter Group, Hybrid & Remote" click on button "Vizualizeaza jobul"
6. go on job icon and after press "Editeaza""
7. checke/ confirm location and type of job, press button "Editati"

EXPECTED RESULTS:
Job for "Workplace Engineer - Flutter Group, Hybrid & Remote" must to be valid.

ACTUAL RESULTS:
Job for "Workplace Engineer - Flutter Group, Hybrid & Remote" is duplicate and error appear when try to validate.
See below screenshot:

https://www.betfairromania.ro/jobs/jr122672/workplace-engineer-flutter-group-hybrid-remote/

![image](https://github.com/user-attachments/assets/21fc1824-b220-407d-84fa-9e795f3d8f16)

**Comment by lalalaurentiu** [comment]
Fixed
