### ISSUE TITLE
Options to remove only one city not all cities 

### ISSUE THREAD

**Issue by IurieChi** [peviitor-ro/validator-ui#62]
ENVIRONMENT: production
URL: https://admin.peviitor.ro/
Browser: Brave
Device: PC
OS: MacOS

STEPS TO REPRODUCE:

1 . Open the URL in the browser and connect to the user.
2. On the page "Companii" type in the search bar the company you wish to review, for example, Chorus, and enter
3. Click the button "Viuzualizeaza joburi"
4. After you have the jobs displayed, go to one of the jobs and click the button "Editati"
5. See the option "Localitatea" and verify if there is an option to delete city which has the options: you could remove delete city

EXPECTED RESULTS:
At the option "Tipul Localitatea" from "Editati" section, to have the option to remove (delete) only one city not all: 

ACTUAL RESULTS:
At the option "Localitatea" there is no option to remove one city, but you can remove all locations.

<img width="1148" alt="Screenshot 2024-05-30 at 12 06 34" src="https://github.com/peviitor-ro/validator-ui/assets/124267735/e6d80728-4790-48b9-8e23-164c1a2b5d0d">

**Comment by lalalaurentiu** [comment]
Added in pull request #94

**Comment by IurieChi** [comment]
well done
