### ISSUE TITLE
Job "Data Scientist" is duplicate in Vodafone page!

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#621]
ENVIRONMENT:
https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
1. enter URL in browser
2. go to "https://admin.peviitor.ro/" and check on search box "Cauta aici ..."
3. insert in box "Vodafone" and press ENTER.
4. go to icone "Vodafone" and press on button "Vizualizeaza joburi"
5. on "Vodafone" page check job  "Data Scientist" click on button "Vizualizeaza jobul"
6. go on job icon and after press "Editeaza""
7. checke/ confirm location and type of job, press button "Editati"

EXPECTED RESULTS:
Job for  "Data Scientist" must to be valid.

ACTUAL RESULTS:
Job for  "Data Scientist" is duplicate and error appear when try to validate.
See below screenshot:

![image](https://github.com/user-attachments/assets/b7c77dcd-2e94-40ab-b5c4-0233eef39266)

**Comment by lalalaurentiu** [comment]
La mine nu apar ... 
<img width="1440" alt="Screenshot 2024-11-18 at 17 40 44" src="https://github.com/user-attachments/assets/0183b22e-42a3-45de-a32c-71d02fb3d497">

**Comment by Cristian-Emil** [comment]
Ca sa nu ridic un alt BUG:

Security Deployment Enablement Lead
https://jobs.vodafone.com/careers/job/563018682801921

Software Developer
https://jobs.vodafone.com/careers/job/563018682802233

Astea 2 sunt duplicate.
