### ISSUE TITLE
The "Editati" button doesn't work on any card across assigned companies

### ISSUE THREAD

**Issue by mihaelaadam** [peviitor-ro/validator-ui#632]
ENVIROMENT: validator UI
URL: https://admin.peviitor.ro/jobs/Expressvpn
**Company_careers_url**: [EXPRESSVPN](https://admin.peviitor.ro/jobs/Expressvpn)
 Desktop:
```
OS: Windows 11
Browser: Chrome
Version: 130.0.6723.70
```

 
### **STEPS TO REPRODUCE:**
1) click on job card: "Senior Product Manager - Marketing Technology"
2) click on "Editeaza" icon
3) select "remote" on "Tipul Jobului" field
4) click on "Editati" button

>**EXPECTED RESULTS:**
1) the "Editare Job" window closes
1) the message "Actiune efectuata cu succes cu succes" is displayed
2) the "Editat" label is visible on the "Senior Product Manager - Marketing Technology" card

>**ACTUAL RESULTS:**
1) page returns an error
2) the window  "Editare Job" stays open
2) job is not updated
<br>

**Screenshots**
![chrome_UsiTMus7VG](https://github.com/user-attachments/assets/3b3f2c77-22b7-45ba-a69b-d5fbba4537e1)

**Comment by lalalaurentiu** [comment]
Fixed
