### ISSUE TITLE
Search field retains previous input when navigating between company job listings

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/validator-ui#634]
ENVIRONMENT: Validator.ui
URL: URL: [Validator](hhttps://admin.peviitor.ro)
 Desktop:
```
OS: Sonoma 14.6.1
Browser: Chrome
Version: 129
```

### **STEPS TO REPRODUCE:**
1) Navigate to the validator webpage and select a company.
2) Click the "Vizualizeaza Joburi" button to view its job listings.
3) Enter a job title in the search field.
4) Use the browser's back button or navigate back to the validator webpage.
5) Select a different company and click "Vizualizeaza Joburi" for its job listings.
6) Observe the jobs listed on the company's official page

>**EXPECTED RESULTS:**
The job listing page for the newly selected company displays all available job cards without any filters or search input applied.

>**ACTUAL RESULTS:**
The job listing page for the newly selected company does not display any jobs because the search field retains the input from the previous company's listing page, applying an unintended filter.

**Comment by lalalaurentiu** [comment]
Fixed
