### ISSUE TITLE
"Genpact" company jobs are published and get unpublished the following day

### ISSUE THREAD

**Issue by Lore78** [peviitor-ro/validator-ui#635]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser.
2. Click on "scraperi".
3. Click on "scrapers_python_iurie".
4. Click on "genpact.py" and run the scraper.
5. Click on "Personal alfabetic".
6. Select "Genpact".

**EXPECTED RESULTS:**
The published jobs should appear in production in the publishing day as well as in the following days.

**ACTUAL RESULTS:**
The published jobs do not appear in production in the following days.

![image](https://github.com/user-attachments/assets/e801212b-835c-4af8-ac9c-7d36835d9a2d)

![image](https://github.com/user-attachments/assets/a70738b8-e891-4477-9433-6b9b534e3079)

![image](https://github.com/user-attachments/assets/b5a782cd-3986-4300-8d21-4dabda34b6d4)

**Comment by lalalaurentiu** [comment]
Fixed
