### ISSUE TITLE
a job still can pe published twice 

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/validator-ui#636]
Environment: validator
Browser: Chrome 123
OS: Windows 10

Steps to reproduce:
1 Open the https://admin.peviitor.ro/
2. Open a company to see its jobs (ex. dornamedical)
3.Choose a new job to publish it 
4. Press on the button "Publica"

Expected results:
The button "Publica" can be used only once and the job is published once.

Actual result :
<img width="1164" alt="job_twice" src="https://github.com/user-attachments/assets/8449dcda-0a46-4b77-a143-cf059b47f04f">

The button "Publica" could be used twice and the job was published twice.

**Comment by lalalaurentiu** [comment]
Fixed
