### ISSUE TITLE
The confirmation label from running scraper disappear after a short time.

### ISSUE THREAD

**Issue by Cristian-Emil** [peviitor-ro/validator-ui#638]
ENVIRONMENT:

https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
1. Enter URL in browser
2. Go to "https://admin.peviitor.ro/" and check "Cont" from top bar
3. Click on "Scraperi"
4. Click on "Actualizeaza" button
5. Click on figure "based_scraper_py" pictures
6. Check "company" scraper
7. Click on "company"  scraper

The confirmation label appera and disappears after a short time.
![image](https://github.com/user-attachments/assets/84fa28d8-4cd4-49ff-836f-68dc8d22b1f6)

It is recommended to have label with confirmation: to close this need to received confirmation from tester - to press click on the label.

**Comment by lalalaurentiu** [comment]
Added..
<img width="1440" alt="Screenshot 2024-12-18 at 15 11 16" src="https://github.com/user-attachments/assets/c8da08aa-b38b-44fc-b009-cfc319f88da1" />
