### ISSUE TITLE
Haleon - Regulatory Affairs Associate - this job doesn't exists anymore on the company's oficial website although in validator it exists

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/validator-ui#65]
URL: https://admin.peviitor.ro/jobs/Haleon
Browser: Chrome
Device: PC
OS: Linux

STEPS TO REPRODUCE:

    Open the URL in the browser
    Click on the logo of the validator
    Go and click inside the searching bar and write "Haleon" 
    Verify the number of jobs to be the same as on the company's official website.

EXPECTED RESULTS:
The number of jobs is the same on validator and on the company's official website.

ACTUAL RESULTS:
On validator appears an extra job which isn't available anymore on the company's oficial website (Regulatory Affairs Associate.

![haleon ](https://github.com/peviitor-ro/validator-ui/assets/129604131/7bb7a370-d944-4063-8692-1f734078d5f5)

![Haleon1](https://github.com/peviitor-ro/validator-ui/assets/129604131/c1b33c41-39be-45f9-b1ec-9a0e9aa13001)

**Comment by lalalaurentiu** [comment]
Fixed
