### ISSUE TITLE
Diacritics or not

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/validator-ui#66]
A saw this situation "Oras: Mureş, Judet: Mures" and I what to know if all the locations need to contain diacritics?

<img width="215" alt="Screenshot at Jun 04 14-53-55" src="https://github.com/peviitor-ro/validator-ui/assets/137428958/096ebb64-d64d-420e-8c28-a021635b158f">

**Comment by lalalaurentiu** [comment]
Orașele din validator nu au diacritice așa sunt aduse de scraper.
