### ISSUE TITLE
"Remove companies" button for the old companies from production

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/validator-ui#67]
ENVIRONMENT: production
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11 Pro

**DESCRIPTION:**

Enter a "Remove companies" button to have access to delete an old company from production. When the user clicks on the button, he should be able to have a list of all the companies from production and the option to delete the desired companies.
This option should be valid for those who have access to share companies to other users.

**EXPECTED RESULTS:**
When you press the "Remove companies
![remove](https://github.com/peviitor-ro/validator-ui/assets/23164347/90df8f1d-0371-4078-b2bd-5b5a120ac76d)
" button, the user should be able to delete an old company from production.

**Comment by lalalaurentiu** [comment]
Added in pull request #71
