### ISSUE TITLE
"Magnaelectronics" Company  - No logo

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/validator-ui#68]
URL: https://peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Click on the "Cauta" button
3. Click on the "Companie" button, writhe "Magnaelectronics" and seletct it in the search bar. 

**OR:**
1. Open the URL in the browser
2. Type a job title from "Magnaelectronics" companie and press  "Cauta" button

Text data: "Agile Program Lead"

**EXPECTED RESULTS:**
"Magnaelectronics" companie should appear with a logo.

**ACTUAL RESULTS:**
"Magnaelectronics" company has no logo.

**Mention:**
"Magnaelectronics" company has the logo on "https://admin.peviitor.ro/".

<img width="307" alt="image" src="https://github.com/peviitor-ro/validator-ui/assets/23164347/7679c3fb-2843-4156-a3ad-c2750f3663e0">

<img width="784" alt="image" src="https://github.com/peviitor-ro/validator-ui/assets/23164347/16fe61bd-d1be-4bdf-a3a9-6a30d92282db">

<img width="303" alt="image" src="https://github.com/peviitor-ro/validator-ui/assets/23164347/3018a5f4-1ae2-4cec-b322-a641f0ad005f">

**Comment by lalalaurentiu** [comment]
Fixed!
