### ISSUE TITLE
"Medlife" Companie - Graphic error and the number of jobs results in peviitor.ro does not coincide with the jobs that are published on Medlife website

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/validator-ui#69]
URL: https://peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Click on the "Cauta" button
3. Click on the "Companie" button, writhe "Medlife" and seletct it in the search bar. Observe the number of jobs results.
4. Open the "Medlife" website ( https://www.medlife.ro/cariere/lista-joburi ). Observe the number of jobs results.

**EXPECTED RESULTS:**
The number of jobs should be identical (70 Jobs)

**ACTUAL RESULTS:**
The number of jobs it is not identical.

<img width="233" alt="image" src="https://github.com/peviitor-ro/validator-ui/assets/23164347/42de2b63-5880-48dd-ac24-7b552e48e405">
<img width="929" alt="image" src="https://github.com/peviitor-ro/validator-ui/assets/23164347/fd37ba82-c8af-41a2-87ae-98d5c8873e50">

<img width="209" alt="image" src="https://github.com/peviitor-ro/validator-ui/assets/23164347/533e6776-7b0f-463e-ae00-e08f014ae852">

**Comment by lalalaurentiu** [comment]
Fixed
