### ISSUE TITLE
Hunedoara county - Duplicated data

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/validator-ui#70]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Click on any companie
3. Click on "Editati" from any job
4. Write on the "Localitatea" field any city, town, common or village from Hunedoara county.

Text data: 
"Deva" , "Petrosani", "Aninoasa" etc.

**EXPECTED RESULTS:**
Search results should appear only once.

**ACTUAL RESULTS:**
Search results appear twice.

<img width="612" alt="image" src="https://github.com/peviitor-ro/validator-ui/assets/23164347/48f0709e-19c7-4929-bd6e-a6ead90cfd24">

<img width="619" alt="image" src="https://github.com/peviitor-ro/validator-ui/assets/23164347/65b9bea2-379d-485e-9e3b-9276be5916ad">

<img width="609" alt="image" src="https://github.com/peviitor-ro/validator-ui/assets/23164347/3c636695-e1aa-49e6-b890-a65f07dc59af">

**Comment by lalalaurentiu** [comment]
Fixed
