### ISSUE TITLE
Satu Mare duplicate "judet" data entry (scrapper:Fildas)

### ISSUE THREAD

**Issue by Omiale** [peviitor-ro/validator-ui#72]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: PC
OS: Windows 10

STEPS TO REPRODUCE:

Open the URL in the browser
Click on any company
Click on "Editati" from any job
Write on the "Localitatea" field Satu mare county.
Text data:
Satu Mare

EXPECTED RESULTS:
Search results should appear only once.

ACTUAL RESULTS:
Search results appear four times with four different :judet: parameters
![Untitled](https://github.com/peviitor-ro/validator-ui/assets/69211506/691c8c5d-7123-4275-9245-3afd681a7085)

**Comment by lalalaurentiu** [comment]
Există toate în România nu e nici un duplicat

- [Satu Mare Jud.Arad](https://ro.m.wikipedia.org/wiki/Satu_Mare,_Arad)
- [Satu Mare Jud.Harghita](https://ro.m.wikipedia.org/wiki/Satu_Mare,_Harghita)
- [Satu Mate Jud.Mehedinti](https://ro.m.wikipedia.org/wiki/Satu_Mare,_Mehedin%C8%9Bi)
- [Satu Mare Jud.Satu Mare](https://ro.m.wikipedia.org/wiki/Satu_Mare)
