### ISSUE TITLE
The scrapper for "Nestle" company it is not working well

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/validator-ui#76]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE:**

1. Open the URL in the browser
2. Click on the search field for "Nestle" company
3. Click on vizualizeaza joburi

**ACTUAL RESULTS:** There is only 1 job and on the graphic are 17 jobs. On the company website are 9 jobs ([link](https://www.nestle.com/jobs/search-jobs?keyword=&country=RO&location=&career_area=All)). 

<img width="925" alt="image" src="https://github.com/peviitor-ro/validator-ui/assets/23164347/63d59ce0-8eed-40a2-8103-8ab4ea1b2d0f">

<img width="946" alt="image" src="https://github.com/peviitor-ro/validator-ui/assets/23164347/ee09096e-ac70-4cbe-bc85-8ac62a875f7c">

**Comment by lalalaurentiu** [comment]
Fixed
