### ISSUE TITLE
The number of the jobs should be displayed near and per filter for (Toate, Publicate, Nepublicate, Editate, Needitate )

### ISSUE THREAD

**Issue by cornel13** [peviitor-ro/validator-ui#77]
ENVIRONMENT:

url: https://admin.peviitor.ro/jobs/Cocacolahbc
browser: chrome
STEPS TO REPRODUCE:

enter url in browser
Go to filter on the right and change from Toate to Nepublicate. It would be nice to have the numbers of Nepublicate jobs near the filter so we don't have to manually count for the jobs. This should be applicable for the rest of the filters. 
For company's with many jobs displaying the numbers of the filters  (Toate, Publicate, Nepublicate, Editate, Needitate ) will help a lot when counting the published jobs from the validator and prod https://peviitor.ro/.

**Comment by lalalaurentiu** [comment]
Adăugat, dar nu lângă filtre ci în cardul companiei. ![image](https://github.com/user-attachments/assets/3d6b36b3-538b-4044-ae90-0ea72e056e66)
Poți vedea numărul joburilor publicate în producție. Sau mai adăugat 2 noi filtre pentru a filtra companiile în funcție de numărul joburilor publicate în producti, ascendent și descendent.![image](https://github.com/user-attachments/assets/11dfbb91-7505-4542-a93b-0e7fbc8bb1f6)
