### ISSUE TITLE
Vonconsulting - the number of jobs in the "Companii" section in validator does not coincide with the number of jobs on the company's graph

### ISSUE THREAD

**Issue by CameliaAM** [peviitor-ro/validator-ui#80]
**ENVIRONMENT**

URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

**STEPS TO REPRODUCE**
1. Open the URL in the browser
2. Write in the search field "Vonconsulting"
3. Click on "Vizualizeaza joburi"

**EXPECTED RESULTS**

The number of jobs of Vonconsulting company from the "Companii" section should be the same with the number of jobs shown of the company's graph

**ACTUAL RESULTS**

On the "Companii" section are shown only 146 jobs, and on the graph are 149.

![Screenshot 2024-06-12 142535](https://github.com/peviitor-ro/validator-ui/assets/34051862/c5429ea1-38f0-4bb4-9025-9bc73e756179)
![Screenshot 2024-06-12 142506](https://github.com/peviitor-ro/validator-ui/assets/34051862/e1c501e6-e92e-4486-9589-c9c6cb34a80d)

**Comment by lalalaurentiu** [comment]
Fixed
