### ISSUE TITLE
Incorrect Job Type Information for TBI Bank Job Listing 

### ISSUE THREAD

**Issue by zahadianamaria** [peviitor-ro/validator-ui#84]
Additional Information:
URL: https://tbibankro.recruitee.com/o/php-full-stack-developer-1
Browser: Chrome
Device: Laptop
OS: Windows 11

Description: The job type for the TBI Bank Job Listing - PHP Full Stack Developer is incorrectly displayed in the validator as hybrid. However, the company's website indicates that the job is onsite

Steps to Reproduce:
1.	Open the validator and navigate to the job listing for TBI Bank Senior Accountant.
2.	Note the job type displayed in the validator (e.g., "Hybrid").
3.	Visit the company's website using the provided link: https://tbibankro.recruitee.com/o/php-full-stack-developer-1
4.	Observe the correct job type on the company's website (e.g., "Onsite").

Expected Result: 
The validator should display the correct job type for the job listing (should be "Onsite").

Actual Result: 
The validator displays the job type as "Hybrid" when the job is actually "Onsite".

**Comment by lalalaurentiu** [comment]
La fel, nici o problema 
<img width="1440" alt="Screenshot 2024-06-18 at 14 31 26" src="https://github.com/peviitor-ro/validator-ui/assets/67306273/0900cad8-ed90-476c-9e44-ab3ac9c1c73c">
<img width="1440" alt="Screenshot 2024-06-18 at 14 31 35" src="https://github.com/peviitor-ro/validator-ui/assets/67306273/a0a8d16a-de91-40be-8d2e-91f1bf62cafc">
