### ISSUE TITLE
Incorrect Location Information for TBI Bank Job Listing - Relationship Manager SME (IMM) CLUJ / IASI

### ISSUE THREAD

**Issue by zahadianamaria** [peviitor-ro/validator-ui#85]
Additional Information:
URL: https://tbibankro.recruitee.com/o/teller-slatina-2
Browser: Chrome
Device: Laptop
OS: Windows 11

Description:
The Tbi Bank Job Listing - Relationship Manager SME (IMM) CLUJ / IASI displays incorrect location information in the validator. According to the company's website, the job is located in Bucharest and Iasi, but the validator incorrectly lists Brasov as one of the locations.

Steps to Reproduce:
1. Open the validator and navigate to the job listing for Tbi Bank Job Listing - Relationship Manager SME (IMM) CLUJ / IASI.
2. Note the counties and cities displayed in the validator (e.g., "Brasov").
3. Visit the company's website using the provided link: https://tbibankro.recruitee.com/o/teller-slatina-2
4. Observe the correct locations on the company's website (e.g., "Bucharest" and "Iasi").

Expected Result:
The validator should display the correct locations for the job listing (should be "Bucharest" and "Iasi").

Actual Result:
The validator displays an incorrect location, including "Brasov", which is not mentioned on the company's website.

**Comment by lalalaurentiu** [comment]
Nu vad nici o problema cu Orasele 
orasele in validator
<img width="1440" alt="Screenshot 2024-06-18 at 14 27 56" src="https://github.com/peviitor-ro/validator-ui/assets/67306273/a3f9f0ba-1569-42c3-a608-a0eefc769227">

orasele pe siteul oficial
<img width="1440" alt="Screenshot 2024-06-18 at 14 28 03" src="https://github.com/peviitor-ro/validator-ui/assets/67306273/956bdc32-b5ed-45e4-8394-87f9f03f953a">
