### ISSUE TITLE
Ensure Consistency Between Job Title and Location Details for Relationship Manager SME (IMM) CLUJ / IASI

### ISSUE THREAD

**Issue by zahadianamaria** [peviitor-ro/validator-ui#86]
Additional Information:

Job Title: Relationship Manager SME (IMM) CLUJ / IASI
URL: https://tbibankro.recruitee.com/o/teller-slatina-2
Browser: Chrome
Device: Laptop
OS: Windows 11

Description:
The job title "Relationship Manager SME (IMM) CLUJ / IASI" includes Cluj in the title, but Cluj is not mentioned in the job description or location details.

Steps to Reproduce:
1. Review the job listing for "Relationship Manager SME (IMM) CLUJ / IASI".
2. Note that Cluj is included in the job title but is absent from the job description and location information.
3. Visit the job listing on the company's website or validator to verify the discrepancy.

Proposed Enhancement:
Update the job title to accurately reflect the job's location or adjust the job description and location details to include Cluj if applicable. This will ensure consistency and clarity for potential applicants.

**Comment by lalalaurentiu** [comment]
Toate datele se pot edita manual. scraperul ce gaseste aia extrage. De acea am creat validatorul

https://github.com/peviitor-ro/validator-ui/assets/67306273/c3ec4695-ef40-453d-85bd-feabfb2479d5
