### ISSUE TITLE
SPYROSOFT - The problem with the difference between the number of jobs is still there from a time to time

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/validator-ui#88]
ENVIRONMENT

URL: https://admin.peviitor.ro/
Browser: Chrome
Devices: PC
OS: Windows 10

STEPS TO REPRODUCE

Open the URL in the browser
Write in the search field "Spyrosoft"
Click on "Vizualizeaza joburi" and verify the number of jobs
Go on production website and verify the number of jobs

EXPECTED RESULTS

The number of jobs on validator is the same with the number of jobs on production .

ACTUAL RESULTS : 
Although few days ago I corrected the problem with the different number of jobs between validator and production, by deleting all the jobs from validator and republishing them, today I saw again that the numbers differ (less on validator than on production), so I had a extra job which isn't available anymore on the official company website 

<img width="1269" alt="jobs numbers" src="https://github.com/peviitor-ro/validator-ui/assets/129604131/a87d35a2-4b22-4179-98b2-f9f9438a897e">

**Comment by lalalaurentiu** [comment]
Încearcă cu noul update din validator cu "sincronizează joburile" și vezi dacă se remediază problema

**Comment by lalalaurentiu** [comment]
Fixed
