### ISSUE TITLE
"justrocket" not found in the Validator search engine

### ISSUE THREAD

**Issue by yonutzu** [peviitor-ro/validator-ui#90]
ENVIROMENT: production
URL: https://admin.peviitor.ro/

 Desktop:
```
OS: Windows 11 PRO
Browser: Chrome
Version: 125.0.6422.142
```

 
### **STEPS TO REPRODUCE:**
1 .Open the URL in the browser
2. Write "justrocket" in the Validator search engine
3. Check the data returned by the scraper

>**EXPECTED RESULTS:**
The scraper returns the "justrocket" card

>**ACTUAL RESULTS:**
The scraper doesn't return the "justrocket" card and the message "no result found" appear
<br>

**Screenshots**
...
![justrocket](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/76839121/227f89a7-e5af-4a84-bd9d-e561e0d3d3d6)

**Comment by cristiol** [comment]
It s not a bug JustRocket doesnn't have jobs anymore
