### ISSUE TITLE
The Burger Menu does not close

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/validator-ui#91]
**ENVIRONMENT**
URL: https://admin.peviitor.ro/
Browser: Chrome
Devices: Laptop
OS: MacOS

**PRECONDITIONS**
The [website](https://admin.peviitor.ro/) is up and running.
At mamiximum width of 1024 (breakpoint).

**STEPS TO REPRODUCE**
1. Open the URL in the browser
2. Resize the window to satisfy the maximum width
3. Click the "Burger Menu" button
4. Click the "CONT" button.
5.  Click the "COMPANII" button

**EXPECTED RESULTS**
After selecting one of these buttons, the menu should close

**ACTUAL RESULTS** 
After selecting one of these buttons, the menu remains open

https://github.com/peviitor-ro/validator-ui/assets/137428958/243b4bd7-22dd-4bcd-89a9-c0a02a032474

**Comment by lalalaurentiu** [comment]
Fixed
