### ISSUE TITLE
Absence of city in Validator

### ISSUE THREAD

**Issue by Amy-Maxima** [peviitor-ro/validator-ui#96]
ENVIROMENT:
URL: https://admin.peviitor.ro/jobs/prysmian
Browser: Chrome
Devices: Laptop
OS: Windows

 
### **STEPS TO REPRODUCE:**
1) Open URL in Browswe
2) Go to validator and click "Editati" button
3) Type "Milcov" in the "Localitatea" input

>**EXPECTED RESULTS:**
You can select the "Milcov" location from the suggested dropdown list

>**ACTUAL RESULTS:**
The dropdown opens, but the location Milcov is not displayed in the "Localitatea" section

[missing1](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/174322254/dfb82289-ef4f-43b7-bcf3-652ee3fe8e72)

**Comment by lalalaurentiu** [comment]
Dacă te referi la [asta](https://ro.m.wikipedia.org/wiki/Comuna_Milcov,_Olt) este comună nu localitate

**Comment by lalalaurentiu** [comment]
@Amy-Maxima imi poți da linkul de la job ca nu am acces la toate companiile

**Comment by Amy-Maxima** [comment]
@lalalaurentiu https://admin.peviitor.ro/jobs/Prysmian
doar acum am vazut comment-ul, sorry
