### ISSUE TITLE
Bigger select field for "Selecteaza Companii" from "Cont" section

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/validator-ui#97]
ENVIRONMENT: Validator UI
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11 Pro

**DESCRIPTION:**

We need a larger select field in the "Select companies" section to be able to select companies more easily. At the moment it is very small and difficult to use. There is also the option to increase or decrease the select field exactly as we need. Also, the select field for "Select Scraper" is too large.

**EXPECTED RESULTS:**
The "Select companies" section has a select field large enough to easily select companies.

**ACTUAL RESULTS:**
The "Select companies" section doesn't have a select field large enough to easily select companies.

![ench1](https://github.com/peviitor-ro/validator-ui/assets/23164347/6bb8fc11-bc7e-4510-bdd1-fd57ab996c82)

**Comment by lalalaurentiu** [comment]
Added...

**Comment by Florin201092** [comment]
It looks great. Thank you
