### ISSUE TITLE
Different folders for different programming languages scrappers

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/validator-ui#98]
ENVIRONMENT: Validator UI
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11 Pro

**DESCRIPTION:**

I suggest that the companies displayed in the validator be divided into folders depending on the programming language used.

**EXPECTED RESULTS:**
There are several folders related to scrapers made in different programming languages.

**ACTUAL RESULTS:**
The companies are not differentiated and are mixed.

<img width="452" alt="image" src="https://github.com/peviitor-ro/validator-ui/assets/23164347/b34e4099-90dc-4c1a-acf7-f991da5d777e">

**Comment by lalalaurentiu** [comment]
Implementat. Scraperele s-au mutat într-o secțiune separată unde le poți filtra în funcție de limbajul de programare.![image](https://github.com/user-attachments/assets/d0b1af59-ab23-42df-aac3-500548181dad)
Poți căuta în acel search field scraperele unei persoane doar scriindu-i numele.![image](https://github.com/user-attachments/assets/e43199b8-7d36-4bbd-bac8-11ebe29b14e8)

**Comment by Florin201092** [comment]
Congratulations!
