### ISSUE TITLE
888Sparkware I could not run the scraper

### ISSUE THREAD

**Issue by cornel13** [peviitor-ro/validator-ui#99]
ENVIRONMENT:

https://admin.peviitor.ro/account
browser: chrome
STEPS TO REPRODUCE:

Enter url in browser

Try to manually run the scraper 888Sparkware 

EXPECTED RESULTS:
The scraper should run without issues

ACTUAL RESULTS:
The scraper does not run and pop an error
Attachments:
![Scraper not running](https://github.com/peviitor-ro/validator-ui/assets/49681058/759aaa94-a615-4c88-88f1-bf9b0f97bc56)

**Comment by lalalaurentiu** [comment]
Fixed
